### ISSUE TITLE
Grafana PGSQL Table Dashboard show 'Unknown DataSource Prometheus-PgSQL'

### ISSUE THREAD

**Issue by myysophia** [Vonng/pigsty#120]
## Granafa操作界面
![f65c50b931cbe7565abe45fa51f1d5e](https://user-images.githubusercontent.com/25994521/165878836-9d9fda02-d112-4bed-b9c3-b8285cbc48bf.png)
## 问题
instance无法带出实例，不能显示出tbales的row、 age 、size .... 等信息。如上图

 Pg的这些属性在dashboard上查看确实很方便，请作者看一下这个issue

    @@毕竟极致可观测性是pigsty的**灵魂**:)

**Comment by Vonng** [comment]
Confirmed & Fixed by https://github.com/Vonng/pigsty/commit/ce87b925cf0949f7add787fc6eae79ab8901b777

Will be released on v1.5
