### ISSUE TITLE
Add pgBouncer auth query mode

### ISSUE THREAD

**Issue by alemacci** [Vonng/pigsty#136]
Query pg_authid to retrieve user’s password from database instead of popoulating userlist.txt

**Comment by Vonng** [comment]
Another viable option is to use local ident `postgres` (`{{ pg_dbsu }}`) directly.
Which may keeps the database simple without predefined functions?
since pgbouncer & postgres are both run with same os user by default

But I'm worried about if there's any drawbacks like security breach.

**Comment by alemacci** [comment]
We already have that policy on pgb_hba.conf so the pgbouncer virtual database con be accessed from pg_dbsu user

```
# local dbsu quick access
local     pgbouncer    postgres                                    peer
```

Considering that PgBouncer become a frontend for the database, i think we can safely remove the rules:

```
# admin user have intranet access to pgbouncer admin
host      pgbouncer    {{ pg_admin_username }}     10.0.0.0/8      {{ pg_pwd_enc }}
host      pgbouncer    {{ pg_admin_username }}     172.16.0.0/12   {{ pg_pwd_enc }}
host      pgbouncer    {{ pg_admin_username }}     192.168.0.0/16  {{ pg_pwd_enc }}
host      all          {{ pg_admin_username }}     0.0.0.0/0       reject
```

As dbuser_dba is not needed to reach virtualdb and dbas should connect directly to database instead of pgb.

Also, the admin_users and stats_users settings on pgbouncer.ini will become:

```
admin_users               = {{ pg_dbsu }}
stats_users                 = {{ pg_dbsu }}, {{ pg_monitor_username }}
```

I am testing locally and it works pretty well :)

**Comment by alemacci** [comment]
Another point of attention is what reported on pgBouncer docs:

`The stored SCRAM secret cannot by itself be used for deriving login credentials.`

So, when **_{{ pgbouncer_auth query }}_** is true and **_{{ pg_pwd_enc }}_** is scram, credential of dbuser_monitor must be written in plain-text on userlist.txt

**Comment by alemacci** [comment]
Merged https://github.com/Vonng/pigsty/commit/f97a4f599ad753bb11b9985a9f37859eb59be399

Let me know what you think :)
