### ISSUE TITLE
grafana-server refuses to start when grafana_database is set to postgres

### ISSUE THREAD

**Issue by alemacci** [Vonng/pigsty#138]
This is because meta database isn't initialized yet.

**Comment by alemacci** [comment]
Moved grafana's service start & provision into pg_register's grafana playbook

Also, added checks on nginx homepage for both grafana & prometheus

https://github.com/Vonng/pigsty/commit/3b8e8774522590b319caf348bf0f88fc4f25f075

**Comment by Vonng** [comment]
guess we can make `grafana_database` & `grafana_pgurl` obsolete.
and make postgres-grafana as an optional docker app.
