### ISSUE TITLE
[DOC] overview/install : Some of the descriptions are not friendly

### ISSUE THREAD

**Issue by mklzl** [Vonng/pigsty#144]
1. doc url

    http://pigsty.cc/zh/docs/overview/install/#%E5%8D%95%E6%9C%BA%E5%AE%89%E8%A3%85

2. description
    ````
    bash -c "$(curl -fsSL http://download.pigsty.cc/get)"  # 下载最新pigsty源代码
    ./download pkg                                         # 可选，下载离线软件包加速
    cd ~/pigsty; ./configure                               # 根据当前环境生成配置
    ./infra.yml                                            # 在当前节点上完成安装
3. Expected behavior

    ````
    bash -c "$(curl -fsSL http://download.pigsty.cc/get)"  # 下载最新pigsty源代码
    cd ~/pigsty; ./download pkg                                         # 可选，下载离线软件包加速
    ./configure                               # 根据当前环境生成配置
    ./infra.yml                                            # 在当前节点上完成安装

**Comment by Vonng** [comment]
fixed, thank you ~
