### ISSUE TITLE
你好，配置了vip和haporxy，目前vip没有挂载到任务node上，这个是为何

### ISSUE THREAD

**Issue by fangfuhaomin** [Vonng/pigsty#150]
这个挂载动作是由谁来操作的，pg数据节点的服务是符合控制的

**Comment by Vonng** [comment]
当 `vip_mode: l2' 时，`service` role中 会为集创建一个 L2 VIP。

使用前提条件是，集群位于同一二层网络中。

**Comment by fangfuhaomin** [comment]
参数配置后没有vip, 需要执行下这个才行，./pgsql.yml -l pg-xsetc  --tag=vip2
