### ISSUE TITLE
更新模板参数后如何下发到pg节点

### ISSUE THREAD

**Issue by fangfuhaomin** [Vonng/pigsty#151]
更新pigsty/templates/tiny.yml后中的参数后，不知道如果下发到pg node中，在pg node中更新了postgresl.conf，pg reload后配置还原了，如何能更新，感谢指导

**Comment by Vonng** [comment]
PostgreSQL / Patroni 一旦创建，绝大多数配置参数都存储在 DCS 中了。需要使用 pg edit-config 动态修改。
