### ISSUE TITLE
pigsty作为分析型数据库性能方面是否可以有像oracle Exadata类似的性能？

### ISSUE THREAD

**Issue by sprite311** [Vonng/pigsty#153]

**Comment by Vonng** [comment]
1. pigsty 不是数据库，而是数据库管控，主要是 PostgreSQL 的管控，类似于本地版的RDS/DBaaS服务
2. 我没有对比过 Oracle/ExaData，PostgreSQL 可以称为 HTAP 数据库，TP性能与AP性能表现都不错
关于 PostgreSQL 在 TP 与 AP 领域的性能基准，可以参考这里 https://github.com/Vonng/pgtpc
