### ISSUE TITLE
我们服务器没有较高权限, 如何使用pigsty

### ISSUE THREAD

**Issue by darkz1984** [Vonng/pigsty#168]
我们服务器用户都是低权限用户, 即非root用户, 没有权限yum安装这样的服务器, pigsty如何定制安装目录, 及最小化组件实现monly模式来部署监控系统监控其他服务器上的pg数据库或者云上的rds实例

**Comment by Vonng** [comment]
仅监控模式只要求你有管理机的root权限，可以参考这里：http://pigsty.cc/zh/docs/deploy/monitor/#%E7%B2%BE%E7%AE%80%E9%83%A8%E7%BD%B2%E4%B8%8E%E6%A0%87%E5%87%86%E9%83%A8%E7%BD%B2%E7%9A%84%E5%8C%BA%E5%88%AB
