### ISSUE TITLE
arm64/aarch64 support on el9 / el8 / ubuntu 22.04

### ISSUE THREAD

**Issue by Vonng** [Vonng/pigsty#171]
To support arm64 on el7 & el8, we have find corresponding rpm for aarch64:

> el9.aarch64 missing too much pgdg packages, maybe later  

### Core

If we have following aarch64 rpm ready, we can init postgres on common nodes.

- [x] pg_exporter https://github.com/Vonng/pg_exporter
- [x] haproxy-rpm https://github.com/Vonng/haproxy-rpm
- [x] vip-manager https://github.com/cybertec-postgresql/vip-manager

### Meta

To run pigsty meta node on aarch64, we have to 

- [x] build prometheus rpm for aarch64 : not found yet
- [x] build grafana rpm : official repo now support grafana 7.5 (current 9.2)

**Comment by gridworkz** [comment]
Thanks for looking at this. Would any of these prometheus repos work?

https://packages-altlinux-org.translate.goog/ru/p9/srpms/prometheus/rpms/?_x_tr_sl=ru&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=sc

**Comment by hartraft** [comment]
Thanks for your work. I really like the idea of pigsty.

Vip manager now has aarch64 [rpms](https://github.com/cybertec-postgresql/vip-manager/releases/download/v2.3.0/vip-manager_2.3.0_Linux_arm64.rpm)
https://github.com/cybertec-postgresql/vip-manager/releases/tag/v2.3.0

What else would be missing? I can have an attempt at a PR if the tasks can be outlined

**Comment by Vonng** [comment]
Resolved, this will be included @ pigsty v3.1
