### ISSUE TITLE
fix haproxy healthcheck with patroni ssl enabled

### ISSUE THREAD

**Issue by Vonng** [Vonng/pigsty#175]
> Comment by @alemacci 
> 
> ```
> default-server inter 3s fastinter 1s downinter 5s rise 3 fall 3 on-marked-down shutdown-sessions slowstart 30s maxconn 3000 maxqueue 128 weight 100 ca-file /etc/pki/ca.crt
>     # service members
>     server pg-clu-1 [192.168.50.71:6432](http://192.168.50.71:6432/) ssl check-ssl port 8008 weight 100
>     server pg-clu-2 [192.168.50.72:6432](http://192.168.50.72:6432/) ssl check-ssl port 8008 weight 100
>     server pg-clu-3 [192.168.50.73:6432](http://192.168.50.73:6432/) ssl check-ssl port 8008 weight 100
> ```
> 
> In default-server line i put the ca-file directive, used to verify client's certificate (when patroni_ssl_enabled is true or pg_sslmode != 'disable')
> If the service is in SSL mode, i put the directive 'ssl' after service port.
> If the health check (patroni port) is using ssl, you put the 'check-ssl' directive instead of 'check'
> 
> It should work

Sounds promising, WIP.

**Comment by alemacci** [comment]
Fixed in https://github.com/Vonng/pigsty/commit/36c86601a7130d133685cd55c25d0b895c6a0119

**Comment by alemacci** [comment]
Fixed with https://github.com/Vonng/pigsty/commit/36c86601a7130d133685cd55c25d0b895c6a0119 and https://github.com/Vonng/pigsty/commit/4819276254cdd979b566073e2ece0c559c9caafd

**Comment by Vonng** [comment]
Work like a charm, thanks ~ ;)

now the only problem would be Prometheus scrape config for the Patroni SSL endpoint.
https://github.com/Vonng/pigsty/issues/195
