### ISSUE TITLE
Use etcd as default and the only DCS implementation

### ISSUE THREAD

**Issue by Vonng** [Vonng/pigsty#178]
`etcd` is more appropriate to be used as DCS for PostgreSQL HA.
Since it does not introduce an agent on target nodes.

The proposal is as follows:

* discard all `dcs_*` parameters, use `etcd_*` instead
* describe etcd with a special group `etcd` instead of `dcs_servers`
* enable dcs ssl by default
* remove consul registry and all service registration logic
* playbook `etcd.yml` for deploying new etcd cluster or add new instance to existing etcd cluster
* playbook `etcd-remove.yml` for removing etcd cluster or remove instance from existing cluster

```bash
./infra.yml
./node.yml
./etcd.yml
./pgsql.yml

```

Rough thoughts.

**Comment by Vonng** [comment]
Now consul is purged, replaced with etcd:

https://github.com/Vonng/pigsty/commit/ffdf7e4ec869f27793fff023a3c22fafbf4a9cf3

**Comment by alemacci** [comment]
I think you unintentionally removed the correct line on files/cmdb.sql

```
-       coalesce((hostvars.vars ->> 'etcd_enabled'::text)::boolean               , TRUE ) AS etcd,
        coalesce((hostvars.vars ->> 'consul_enabled'::text)::boolean             , TRUE ) AS consul,
```

**Comment by Vonng** [comment]
> I think you unintentionally removed the correct line on files/cmdb.sql
> 
> ```
> -       coalesce((hostvars.vars ->> 'etcd_enabled'::text)::boolean               , TRUE ) AS etcd,
>         coalesce((hostvars.vars ->> 'consul_enabled'::text)::boolean             , TRUE ) AS consul,
> ```

Overhaul on API, will fix that later ;)
