### ISSUE TITLE
Dumb noob questions

### ISSUE THREAD

**Issue by kubeworkz** [Vonng/pigsty#196]
Couple questions:
1) How do I create / manage databases on the Pigsty instance?
2) Do I use something like pgadmin4?
3) Can multiple people create isolated dbs on Pigsty?
Cheers, Dave

**Comment by Vonng** [comment]
FYI: https://github.com/Vonng/pigsty/blob/v1.5.1/docs/d-deploy.md

**Comment by kubeworkz** [comment]
Perfect, thanks
