### ISSUE TITLE
Supabase support: use pigsty's HA PG as external database

### ISSUE THREAD

**Issue by yoonghm** [Vonng/pigsty#216]
Hi, 

Could the following software be added too

1. PostgREST https://github.com/PostgREST/postgrest
1.  Realtime https://github.com/supabase/realtime

This would really help in development and deployment.  Thanks

**Comment by Vonng** [comment]
Pigsty already provides a PostgREST docker-compose template.
https://github.com/Vonng/pigsty/tree/master/app/postgrest

maybe we can add a supabase template in next release

**Comment by Vonng** [comment]
To run supabase on Pigsty's PostgreSQL, the following extensions has to be compiled into RPMs

- [x] pgsodium (PGDG)
- [x] pg_graphql (RUST)
- [x] pgjwt
- [ ] pg_net
- [ ] supabase_vault

**Comment by Vonng** [comment]
Resolved by https://github.com/Vonng/pigsty/commit/068c84888b4209a8df635a5c992007a34f1614b2
will be release in v2.4.1
