### ISSUE TITLE
Local pigsty repo doesn't cover all packages.

### ISSUE THREAD

**Issue by nusgnaf** [Vonng/pigsty#233]
Hi
While playing with the default demo setup, I noticed constant failure while installing node packages on pg-test cluster. Further investigation revealed that the generic node will nuke all default repo, and install from pigsty local repo only. Unfortunately by default the repo_packages doesn't cover all node_packages as defined in files/cmdb.sql. As a temp fix, I have to define 
`node_repo_remove: false`

**Comment by Vonng** [comment]
Yes, that is what `node_repo_remove` intended for. Existing repo files will be moved to `/etc/yum.repos.d/backup` by default.

I'd like to investigate missing rpms; which rpms are missing on what platforms? ;)

**Comment by nusgnaf** [comment]
Hi, I am using rockylinux 9.1, I noticed that the yum-utils is the root cause.
`failed: [192.168.10.12] (item=lz4,unzip,bzip2,zlib,yum,pv,jq,git,ncdu,make,patch,bash,lsof,wget,uuid,tuned,chrony,perf,nvme-cli,numactl,grubby,sysstat,iotop,htop,yum,yum-utils) => {"ansible_facts": {"pkg_mgr": "dnf"}, "ansible_loop_var": "item", "changed": false, "failures": ["No package yum-utils available."], "item": "lz4,unzip,bzip2,zlib,yum,pv,jq,git,ncdu,make,patch,bash,lsof,wget,uuid,tuned,chrony,perf,nvme-cli,numactl,grubby,sysstat,iotop,htop,yum,yum-utils", "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}
`
I noticed that yum-utils is missing from repo_packages in files/cmdb.sql. But I am not sure how to add it back to the list.

**Comment by nusgnaf** [comment]
Ok, I managed to understand the logic: All node_default_packags should be added in repo_packages , so the simplist fix is to append yum-utils to repo_packages defined in ' roles/repo/defaults/main.yml'
[repo-tweak.patch](https://github.com/Vonng/pigsty/files/10765701/repo-tweak.patch)

**Comment by Vonng** [comment]
Thanks for your feedback 😄.

Resolved by [add yum-utils dnf-utils to repo_packages](https://github.com/Vonng/pigsty/commit/668e1cf8c8c5bafe9be8ceafd95d1c856187e110)

Will be schedule to next RC release.

**Comment by nusgnaf** [comment]
Thanks. It seems dnf-utils is a replacement for yum-utils? Anyway, problem is solved
