### ISSUE TITLE
Alibaba Cloud Linux

### ISSUE THREAD

**Issue by gnsilence** [Vonng/pigsty#234]
Whether it can support  Alibaba Cloud Linux?
It is fully compatible with centos RHEL 7,RHEL 8

**Comment by Vonng** [comment]
Well if it's **fully** compatible with EL 7, EL8. I think it can works.
 
Unluckily I did't find a vagrant box for Alibaba Cloud Linux which I can not test it locally.

**Comment by gnsilence** [comment]
> Well if it's **fully** compatible with EL 7, EL8. I think it can works.
> 
> Unluckily I didn't find a vagrant box for Alibaba Cloud Linux which I can not test it locally.

![image](https://user-images.githubusercontent.com/18021366/221151148-d2a0e4fd-4796-41e0-a1c2-b02f9d7d012e.png)

The local test image can access this link:  https://help.aliyun.com/document_detail/215519.htm?spm=a2c4g.11186623.0.0.47b92b9bSFwT85#task-2078765

**Comment by Vonng** [comment]
You can try dirty hack `configure` L177 script and comment those release check. Which is introduced in official v2.0.0 release: 

https://github.com/Vonng/pigsty/commit/0e0a8f0fb4a26a5ab3bb12163b8c5acd4b9a59d3#diff-90d08e583c4c9c6f391b2ae90f819f600a6326928ea9512c9e0c6d98e9f29ac2

**Comment by Vonng** [comment]
resolved by [loose os release check in bootstrap script](https://github.com/Vonng/pigsty/commit/a7e6fe323b7960e7079ab2422cc1b94f04b78eec)
