### ISSUE TITLE
Pigsty v2.0.0 Release Schedule

### ISSUE THREAD

**Issue by Vonng** [Vonng/pigsty#236]
Pigsty v2.0.0 will be released before March. Here are some 

- [x] The final build: v2.0.0
- [x] Testing in local sandbox
- [x] Update CDN packages
- [x] Passing security checks
- [x] Testing in production
- [x] Pigsty 2.0 En Docs
- [x] Publish Release before 2023/02/28 
- [x] Update https://pigsty.cc/en/ website: English
- [x] Update https://pigsty.cc/zh/ website: Chinese
- [x] Annoucing Pigsty 2.0
  - [ ] PG Conf China 2022 @ 2023/03/03
  - [ ] PostgreSQL.org News  
  - [x] Postgres Weekly
  - [ ] Reddit
  - [ ] Product Hunt
  - [ ] Hacker News
  - [ ] Wechat Platform

**Comment by carfieldboy** [comment]
hi 
i have tested  Pigsty v2.0.0 rc1、rc2 and Pigsty v2.0.0

but encounter this error ,

TASK [pgsql : check replication connectivity] *******************************************************
skipping: [IPADDRESS]
fatal: [IPADDRESS1]: FAILED! => {"changed": true, "cmd": ["psql", "-w", "-h", "unknown", "-p", "5432", "-U", "replicator", "-d", "postgres", "-Atc", "SELECT 1;"], "delta": "0:00:00.736379", "end": "2023-02-27 18:25:01.599017", "msg": "non-zero return code", "rc": 2, "start": "2023-02-27 18:25:00.862638", "stderr": "psql: error: could not translate host name \"unknown\" to address: Name or service not known", "stderr_lines": ["psql: error: could not translate host name \"unknown\" to address: Name or service not known"], "stdout": "", "stdout_lines": []}
fatal: [IPADDRESS2]: FAILED! => {"changed": true, "cmd": ["psql", "-w", "-h", "unknown", "-p", "5432", "-U", "replicator", "-d", "postgres", "-Atc", "SELECT 1;"], "delta": "0:00:00.711378", "end": "2023-02-27 18:25:01.659393", "msg": "non-zero return code", "rc": 2, "start": "2023-02-27 18:25:00.948015", "stderr": "psql: error: could not translate host name \"unknown\" to address: Name or service not known", "stderr_lines": ["psql: error: could not translate host name \"unknown\" to address: Name or service not known"], "stdout": "", "stdout_lines": []}

could you give me some help,thanks!

**Comment by Vonng** [comment]
> hi i have tested Pigsty v2.0.0 rc1、rc2 and Pigsty v2.0.0
> 
> but encounter this error ,
> 
> TASK [pgsql : check replication connectivity] ******************************************************* skipping: [IPADDRESS] fatal: [IPADDRESS1]: FAILED! => {"changed": true, "cmd": ["psql", "-w", "-h", "unknown", "-p", "5432", "-U", "replicator", "-d", "postgres", "-Atc", "SELECT 1;"], "delta": "0:00:00.736379", "end": "2023-02-27 18:25:01.599017", "msg": "non-zero return code", "rc": 2, "start": "2023-02-27 18:25:00.862638", "stderr": "psql: error: could not translate host name "unknown" to address: Name or service not known", "stderr_lines": ["psql: error: could not translate host name "unknown" to address: Name or service not known"], "stdout": "", "stdout_lines": []} fatal: [IPADDRESS2]: FAILED! => {"changed": true, "cmd": ["psql", "-w", "-h", "unknown", "-p", "5432", "-U", "replicator", "-d", "postgres", "-Atc", "SELECT 1;"], "delta": "0:00:00.711378", "end": "2023-02-27 18:25:01.659393", "msg": "non-zero return code", "rc": 2, "start": "2023-02-27 18:25:00.948015", "stderr": "psql: error: could not translate host name "unknown" to address: Name or service not known", "stderr_lines": ["psql: error: could not translate host name "unknown" to address: Name or service not known"], "stdout": "", "stdout_lines": []}
> 
> could you give me some help,thanks!

Resloved... 
you can open another issue for that...
