### ISSUE TITLE
Kubernetes deployment support for Pigsty

### ISSUE THREAD

**Issue by kesavkolla** [Vonng/pigsty#239]
Is there any roadmap for k8s deployment?

**Comment by Vonng** [comment]
There are about 5+ kubernetes operators for PostgreSQL. I think the community really does not need another one.
We are focusing on shipping a PostgreSQL 'operator' that works on BMs & VMs, but open to adding a experimental k8s deployment with something like sealos.

**Comment by tobiasmuehl** [comment]
Please don't ever make a k8s version out of pigsty. You will have to spend way too much effort on dealing with various limitations of k8s, and some features of pigsty will have to be removed. There's no feature that's helpful for running a database cluster which is available in k8s but not available in pigsty

**Comment by Vonng** [comment]
we decide not to do that inside kubernetes:

《[Database in Kubernetes: Is that a good idea?](https://medium.com/@fengruohang/database-in-kubernetes-is-that-a-good-idea-daf5775b5c1f)》

Alas, we do can support to deploy Kubernetes with the help of [Sealos](https://sealos.io/)
