### ISSUE TITLE
自定义数据库的版本

### ISSUE THREAD

**Issue by dengjoy2000** [Vonng/pigsty#249]
目前pigsty新版本总是适配最新的pg数据库，在很多情况下最新版本的数据库并不是最合适的选择，因此pigsty能否有一个自定义数据库版本的功能，我看了下pigsty2.0，如果要换成pg14/13工作量还是蛮大的，而且也不好保证内部组件的兼容性。谢谢。

**Comment by Vonng** [comment]
可以提供一个旧版本参考配置文件，用于 12 - 14 版本的 PG。计划从 2.0 之后保留所有未 EOL 版本。
