### ISSUE TITLE
[BUG REPORT]  Repository confusion

### ISSUE THREAD

**Issue by cocoonkid** [Vonng/pigsty#254]
/etc/yum.repos.d/* is being moved to  /etc/yum.repos.d/backup  but this makes these repo sources unavailable to the system.

pigsty-local.repo file should just be copied to   /etc/yum.repos.d/

The backup operation should be a copy not a move.

![image](https://user-images.githubusercontent.com/43231640/225675073-dad26742-4ad3-4253-911e-86006217d09d.png)

**Comment by cocoonkid** [comment]
In addition I found that the pg-test does not work since the pigsty repos are not being deployed to targets.

rsyncing these manually from a node created locally (not via ansible from remote ) fixed the issue for me.

**Comment by cocoonkid** [comment]
It also fails  here because the local repo is not "properly" installed. rsyncing is not enough :)

![image](https://user-images.githubusercontent.com/43231640/225738177-e2c18471-1754-4d92-b56b-394be6cb2e5c.png)

**Comment by Vonng** [comment]
This behavior is controlled by [`repo_remove`](https://vonng.github.io/pigsty/#/PARAM?id=repo_remove). 

* `true` (default) will move existing repos to the backup dir to assure no confliction & increase speed and stability. 
* `false` will leave existing repos there.

Which is true by default.

Common nodes will use the repo on the admin node through a temp nginx server @ 80/443.

which will be added by:

```bash
./node.yml -t node_repo
```

**Comment by Vonng** [comment]
Add backup repo back during `bootstrap` : 

resolved by [enhancement: add back default repo to /etc/yum.repos.d/ after bootstrap](https://github.com/Vonng/pigsty/commit/ce339c0b8dd5f1adb73127d13f92a7892aabdd3d)

And later the behavior during REPO/NODE can be determined by [`repo_remove`](https://vonng.github.io/pigsty/#/PARAM?id=repo_remove) and [`node_repo_remove`](https://vonng.github.io/pigsty/#/PARAM?id=node_repo_remove)

Will be scheduled in next release.
