### ISSUE TITLE
[Bug Report]  TASK pgsql : remove postgres metadata from etcd

### ISSUE THREAD

**Issue by cocoonkid** [Vonng/pigsty#255]
![image](https://user-images.githubusercontent.com/43231640/225736287-913d5158-12db-4bc0-a4b2-9c89e7d4c858.png)

This always fails but as one can see the earlier steps work so this is NOT an issue of the server not being availabe.

I am not sure what it is but the error message might be a red herring.

**Comment by cocoonkid** [comment]
Commented it our for now to continue testing deployment.

**Comment by Vonng** [comment]
looks like you don't have ssh access to admin node(the node itself) as root.

Luckily we don't really need root for that so fixed by [use current admin user instead of root when delete metadata from dcs
](https://github.com/Vonng/pigsty/commit/99f61b3cc9f633ad867f227b602ea59eeeeead58)

**Comment by cocoonkid** [comment]
@Vonng  As you can see from the tasks before the access is there and valid.

It  throws the error but when commenting the task it continues.
So the issue is not really about access. ansible timeout is set to 60s. 
Not sure what the reason is. Will investigate further.
