### ISSUE TITLE
[BUG REPORT ] TASK [pgsql : generate pg private key]  fails because directory is not existing beforehand

### ISSUE THREAD

**Issue by cocoonkid** [Vonng/pigsty#256]
```
TASK [pgsql : generate pg private key] ********************************************************************************************************************************
fatal: [pg-leader -> localhost]: FAILED! => {"changed": false, "msg": "The directory files/pki/pgsql does not exist or the file is not a directory", "name": "files/pki/pgsql"}
```

Not yet sure how to fix.

My apology for not putting in pull requests. But need to fully understand.

**Comment by Vonng** [comment]
This directory is created during CA setup:

```bash
./infra.yml -t ca_dir
```

Which will create `files/pki/{ca,csr,misc,etcd,nginx,infra,pgsql,minio}` dirs

**Comment by cocoonkid** [comment]
Thanks, I ended up creating them manually and also generating the keys manually.

It seems it doesn't get triggered with pg_test 3 node cluster.

**Comment by cocoonkid** [comment]
Yes, works.
