### ISSUE TITLE
[Bug Report] RHEL/ROCKY9.1 there seems to be a systemd service naming difference

### ISSUE THREAD

**Issue by cocoonkid** [Vonng/pigsty#259]
Currently at 
![image](https://user-images.githubusercontent.com/43231640/225856266-b9960b9e-ce84-4a4d-a93d-6a5888d35506.png)

`$ systemctl start postgres.service`
does  FAIL because database init failed 
```
Mar 17 01:52:49 pg-test-1 postgresql-15-check-db-dir[88521]: "/pg/data" is missing or empty.
Mar 17 01:52:49 pg-test-1 postgresql-15-check-db-dir[88521]: Use "/usr/pgsql-15/bin/postgresql-15-setup initdb" to initialize the database cluster.
Mar 17 01:52:49 pg-test-1 postgresql-15-check-db-dir[88521]: See /usr/share/doc/postgresql15/README.rpm-dist for more information.
Mar 17 01:52:49 pg-test-1 systemd[1]: postgres.service: Control process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
```

database init fails
` /usr/bin/postgresql-15-setup initdb `

reason
systemd service template creates postgres.service
but should be postgresql-15.service in case of Rocky 9.1

`cp /usr/lib/systemd/system/postgres.service /lib/systemd/system/postgresql-15.service`
solved the issue.

` /usr/bin/postgresql-15-setup initdb `
works now.

BUT running the pg-test playbook switches the state back which makes sense of course.

But where is this referenced?  I'm not groking it.

**Comment by cocoonkid** [comment]
Fixed it temporarily by creating a hardlink.

`ln /usr/lib/systemd/system/postgres.service /lib/systemd/system/postgresql-15.service`


And then
`/usr/bin/postgresql-15-setup initdb`

**Comment by Vonng** [comment]
That `postgres.service` is prepared for patroni-less mode which is rarely used.

The postgres service is managed by `patroni.service`.

**Comment by Vonng** [comment]
actually non of that matter's since we don't really use:

- `postgres.service`
- `postgresql.service`
- `postgresql-$version.service`

**Comment by cocoonkid** [comment]
How is postgres initiaited?

I found that if` ln /usr/lib/systemd/system/postgres.service /lib/systemd/system/postgresql-15.service `is missing I can't run 
`/usr/bin/postgresql-15-setup initdb
`
on RL9.1

@Vonng 

Please lmk. ;-)

Will continue testing later today.

**Comment by Vonng** [comment]
Postgres is automatically inited by patroni.
