### ISSUE TITLE
grafana首页 HAproxy连接问题

### ISSUE THREAD

**Issue by lujay** [Vonng/pigsty#26]
小白刚刚初始化完成pigsty集群 在首页
![image](https://user-images.githubusercontent.com/6263244/109096010-ba83ec00-7757-11eb-8fd4-26cd4f90b7ed.png)  这个lian'jie链接不应该是 h.pigsty 么，   目前的超链接好像是 pigsty:9101
![image](https://user-images.githubusercontent.com/6263244/109096088-df785f00-7757-11eb-94e5-4562c9d8a702.png)

其他几个链接都是正常的, 还请指教

**Comment by Vonng** [comment]
Please access http://h.pigsty instead.
Fixed by https://github.com/Vonng/pigsty/commit/8edc1da0c3e11e6cf4851c86395daa6a32ce67b1
Thanks for the feedback

**Comment by lujay** [comment]
谢谢解答
