### ISSUE TITLE
[Bug report]  Patroni & etcd can't connect because of CA mismatch

### ISSUE THREAD

**Issue by cocoonkid** [Vonng/pigsty#261]
etcd.conf

![image](https://user-images.githubusercontent.com/43231640/225903726-05ebeabe-1465-41d8-b3dc-3be535f5fcc3.png)
![image](https://user-images.githubusercontent.com/43231640/225904014-668b3773-6789-4867-bd62-07471bfc8b66.png)

patroni.conf

![image](https://user-images.githubusercontent.com/43231640/225903801-4e51aaec-3d67-4db6-9316-76c1f59cccc6.png)
![image](https://user-images.githubusercontent.com/43231640/225903906-9a87d342-990f-4127-a6be-3c7ec074e07b.png)

I found that 
 cat /etc/pki/ca.crt
& 
cat /etc/etcd/ca.crt 

differ.

But they seem to be correctly set e.g /etc/etcd/ca.crt  should not be in use?

**Comment by Vonng** [comment]
These two cert should be exact same.
I wonder if your deployment has generate another CA somewhere elese. 

Beware that pigsty source (project home) contain states in `files/pki`.

**Comment by Vonng** [comment]
Maybe we can add another variable to control where to put the ca stuff.

```yaml
ca_dir: `pki`      # where to put ca/pki stuff 
```

we can still use `pki` by default which will use `files/pki` in pigsty home. Or specify another dir such as `~/.pigsty/pki` instead. So if you accidently delete pigsty source directory, the certs are still there.
