### ISSUE TITLE
Connecting remotely

### ISSUE THREAD

**Issue by kubeworkz** [Vonng/pigsty#263]
My users would like to connect to our pigsty instance remotely. What is the general format of the connection string they should use?

**Comment by Vonng** [comment]
Check this: https://vonng.github.io/pigsty/#/PGSQL-HBA?id=client-authentication

Beware that default hba does not allow world (public internet) access except for admin user with SSL cert.

```bash
- {user: '${admin}'   ,db: all         ,addr: world     ,auth: cert  ,title: 'admin @ everywhere with ssl & cert'   }
-
```

If you wish to access through the Internet, beware to change [`pg_hba_rules`]

**Comment by kubeworkz** [comment]
Thanks
