### ISSUE TITLE
If a node user changes to zsh we got issues.

### ISSUE THREAD

**Issue by cocoonkid** [Vonng/pigsty#274]
![image](https://user-images.githubusercontent.com/43231640/232106513-7f1ae766-aa19-4a99-998f-5bd39236a7b0.png)

I'd suggest moving the profiles.d/node.sh content directly to .bashrc ? 

Otherwise zsh wants to autoexecute it.

**Comment by Vonng** [comment]
make sense. looking into it

**Comment by Vonng** [comment]
resolved by [use shopt and PS1 when using bash](https://github.com/Vonng/pigsty/commit/95c6e8b3e077d46bef6bde1406817e48782504a9)
