### ISSUE TITLE
add support for anolis

### ISSUE THREAD

**Issue by darkz1984** [Vonng/pigsty#276]
I use anolis 8, when execute ./bootstrap,
shows 
```
[FAIL] release = unknown, /etc/redhat-release not exists
```
I copy /etc/os-release to /etc/redhat-release and it run ok
I think it shoud be work in pigsty

**Comment by Vonng** [comment]
resolved by [loose os release check in bootstrap script](https://github.com/Vonng/pigsty/commit/a7e6fe323b7960e7079ab2422cc1b94f04b78eec)
