### ISSUE TITLE
集群三台节点的高可用问题

### ISSUE THREAD

**Issue by dhx920** [Vonng/pigsty#277]
操作过程：
集群一主两从，数据库使用VIP:192.168.3.233:6432连接
![image](https://github.com/Vonng/pigsty/assets/22776331/8e9f71d9-bd99-4de4-bc12-ddec9a9bece1)
此时三台机器的vip-manager都是开启状态
![image](https://github.com/Vonng/pigsty/assets/22776331/262d2c90-e03b-4b7b-aad4-2d5b747714b7)
![image](https://github.com/Vonng/pigsty/assets/22776331/fbbeac4c-8711-4829-b81e-dde29f7fa135)
![image](https://github.com/Vonng/pigsty/assets/22776331/73c01d07-6c89-4129-9d4a-9f72970b264d)
先把217节点重启，主节点变为了219，数据库能正常连接
![image](https://github.com/Vonng/pigsty/assets/22776331/3fd23989-8266-473b-9c4a-5e9deac270d5)
![image](https://github.com/Vonng/pigsty/assets/22776331/e7158588-3034-4e7a-8ab7-40679e156a6e)
但是重启后的217的vip-manager是未开启状态
![image](https://github.com/Vonng/pigsty/assets/22776331/a691b43d-af09-430e-942e-e72143557995)
再重启219（当前的主节点），
![image](https://github.com/Vonng/pigsty/assets/22776331/77199bf8-8651-45aa-8732-8a74745b4eb1)
重新选举的主节点是218（vip-manager是开启状态的），数据库能正常访问。
当前集群中，218是主节点，vip-manager是开启状态的，而217和219因为前两次的重启，vip-manager为未开启状态，此时重启主节点218，217变为了主节点，因为vip-manager是未开启的，导致数据库连接不上
![image](https://github.com/Vonng/pigsty/assets/22776331/34a501df-ac71-4524-b77f-8b2f6073257a)
![image](https://github.com/Vonng/pigsty/assets/22776331/05b6796a-a7ec-4435-90f0-ae05b15636c4)
而此时需要在217执行$ service vip-manager start 数据库才能连接成功

出现问题的原因：vip-manage服务在节点重启后没有自启动（etcd和patroni会自动启动）
期待结果：能够自动实现高可用

**Comment by Vonng** [comment]
操作系统是？

**Comment by dhx920** [comment]
执行这个命令后可以了
ansible all -f 1 -b -a 'systemctl enable vip-manager'
