### ISSUE TITLE
Discord Invite Link expired

### ISSUE THREAD

**Issue by tobiasmuehl** [Vonng/pigsty#279]
Readme and Wiki both have a link to Discord, but the link actually expired. Most of the user groups of pigsty seem to be mainly in Chinese, is there a space for English speaking users?

**Comment by Vonng** [comment]
Sorry for dead links. https://discord.gg/hG7GYDdW

Updated @ branch v2.1

We try our best to use English in Github / Discord / Telegram as much as we can ;)
