### ISSUE TITLE
[SECURITY ISSUES]Could we consider randomly generating sub domains to avoid exposing services on the internet？

### ISSUE THREAD

**Issue by KaiwenWang** [Vonng/pigsty#281]
Pigsty is great, but for small companies or individuals, the testing method is often to open an ECS and refer to the documentation for installation. However, the problem with this method is that after port 80 is exposed and discovered by the scanner, you can refer to the page content accessed by the IP and configure the host to access the service without a password.

Of course, the formal environment must avoid being exposed to the public network.

So can we consider randomly generating domain names such as h/g/a/p in the h.pigsty domain name, and not exposing specific domain names to the page (or prompting users to customize and configure these domains in the document) to improve security and prevent security issues caused by forgetting to delete network ACLs after rapid testing.

Although this idea can only be patched, it can increase the cost of malicious access after being scanned and prevent leakage.

**Comment by Vonng** [comment]
Port 80 is configurable through `nginx_port`. As for the domain names , they can be configured via `infra_portal`. So maybe it's better to leave those to users.
