### ISSUE TITLE
New Extension: `PostgresML`

### ISSUE THREAD

**Issue by KaiwenWang** [Vonng/pigsty#282]
PostgresML is great. Maybe it will become a new ml model serving entry. Is there any plan to add it to pigsty?

**Comment by Vonng** [comment]
We found a way to build & package the PostgresML extension.

https://postgresml.org/docs/guides/setup/v2/installation

- [ ] Add `python3.11-pip` into repo_packages
- [x] Compile PostgresML with `cargo` and `pgrx`
- [ ] Tutorial: how to install & setup PostgresML Python env

**Comment by Vonng** [comment]
Resolved by https://github.com/Vonng/pigsty/commit/a032b4a10f537c7900d0b1362a848bbb5efefe5b
