### ISSUE TITLE
No package matching 'ncdu' found available, installed or updated

### ISSUE THREAD

**Issue by mawenbin666** [Vonng/pigsty#286]
The installation process reported the following error after executing . /install.yml and the following error is reported:

`TASK [install default node packages] *****************************************************************
failed: [192.168.34.13] (item=[u'lz4,unzip,bzip2,zlib,yum,pv,jq,git,ncdu,make,patch,bash,lsof,wget,uuid,tuned,chrony,nvme-cli,numactl,grubby,sysstat,iotop,htop,yum,yum-utils', u'wget,netcat,socat,rsync,ftp,lrzsz,s3cmd,net-tools,tcpdump,ipvsadm,bind-utils,telnet,dnsmasq,audit,ca-certificates,openssl,openssh-clients,readline,vim-minimal', u'node_exporter,etcd,mtail,python3,python3-pip,python3-idna,python3-requests,haproxy']) => {"ansible_facts": {"pkg_mgr": "yum"}, "ansible_loop_var": "item", "changed": false, "item": ["lz4,unzip,bzip2,zlib,yum,pv,jq,git,ncdu,make,patch,bash,lsof,wget,uuid,tuned,chrony,nvme-cli,numactl,grubby,sysstat,iotop,htop,yum,yum-utils", "wget,netcat,socat,rsync,ftp,lrzsz,s3cmd,net-tools,tcpdump,ipvsadm,bind-utils,telnet,dnsmasq,audit,ca-certificates,openssl,openssh-clients,readline,vim-minimal", "node_exporter,etcd,mtail,python3,python3-pip,python3-idna,python3-requests,haproxy"], "msg": "No package matching 'ncdu' found available, installed or updated", "rc": 126, "results": ["lz4-1.7.5-3.el7.x86_64 providing lz4 is already installed", "unzip-6.0-24.el7_9.x86_64 providing unzip is already installed", "bzip2-1.0.6-13.el7.x86_64 providing bzip2 is already installed", "zlib-1.2.7-18.el7.x86_64 providing zlib is already installed", "yum-3.4.3-168.el7.centos.noarch providing yum is already installed", "pv-1.4.6-1.el7.x86_64 providing pv is already installed", "jq-1.6-2.el7.x86_64 providing jq is already installed", "git-1.8.3.1-23.el7_8.x86_64 providing git is already installed", "No package matching 'ncdu' found available, installed or updated"]}`

How can I fix it?

**Comment by mawenbin666** [comment]
After installing ncdu, another error occurs:
`No package matching 'nvme-cli' found available, installed or updated`

**Comment by Vonng** [comment]
What is your OS release version?

AFAIK, some packages does not have the same name amoung different distributions.

For example, `nc` & `netcat`.

You may consider removing  (overwrite) them in the [`node_packages`] parameter.

Since `nvme-cli` and `ncdu` are not critical packages.
