### ISSUE TITLE
Debian 12 Support

### ISSUE THREAD

**Issue by chikkujimmy** [Vonng/pigsty#293]
Following up with reference to the issue https://github.com/Vonng/pigsty/issues/53 to check if there are any break throughs in setting up pigsty on any Debian flavored OS? Also is it possible to run pigsty on docker containers or are there any complications in doing so?

**Comment by chikkujimmy** [comment]
@Vonng thanks for the update.

**Comment by Vonng** [comment]
Debian 11 & 12 is supported, will be released in v2.5.0
