### ISSUE TITLE
Support for Custom Redis Versions (e.g., Redis 6) in Pigsty 2.3

### ISSUE THREAD

**Issue by M-MoMoMo** [Vonng/pigsty#299]
Hi there,

I hope this message finds you well. I've been using Pigsty for my projects, and I'm quite impressed with its features and capabilities. However, I've encountered a situation where I'd like to use a different Redis version, such as Redis 6, instead of the currently supported Redis 7.2.

I would like to inquire if there are any plans to introduce the ability to customize the Redis version within Pigsty 2.3. Specifically, I am interested in using Redis 6 due to certain requirements in my environment. As of now, Pigsty supports Redis 7.2. Having the flexibility to choose different Redis versions would greatly enhance the adaptability of Pigsty to various use cases.

Compatibility with specific project requirements. Ability to leverage unique features in Redis 6.

Is there any roadmap or consideration to allow users to select and use different Redis versions within Pigsty? If not, would this be something the project could consider in the future?

Thank you for your time and effort in maintaining this fantastic project. I look forward to your insights on this matter.

Best regards

**Comment by Vonng** [comment]
That do make sense, I'll consider adding redis 6 in next release.

**Comment by Vonng** [comment]
First and foremost, thank you for reaching out and sharing your feedback on Pigsty. We truly appreciate users like you who take the time to provide valuable insights and suggestions.

Regarding your query about Redis versions, I understand your concern. The major version of Redis is not part of the package name, which can indeed lead to some confusion and challenges.

As a workaround for your specific requirement, you might consider the following steps:

After installing Pigsty, navigate to /www/pigsty.
Remove the Redis 7.2 package.
Replace it with the Redis 6 package of your choice.
This should allow you to use Redis 6 within Pigsty while we consider more flexible versioning options for future releases.
