### ISSUE TITLE
Can not connect to some nodes from meta node

### ISSUE THREAD

**Issue by lujay** [Vonng/pigsty#30]
172.16.121.232  元节点
172.16.121.233  pg节点1 primary
172.16.121.234  pg节点2 从
172.16.121.235  pg节点3 从
172.16.121.236  源节点vip
172.16.121.237   pg cluster vip
集群初始化完成后（all）， 发现 元节点 无法ping通 primary  pg节点3 
![image](https://user-images.githubusercontent.com/6263244/109098078-94f8e180-775b-11eb-8bd7-64c12f74a9a4.png)
![image](https://user-images.githubusercontent.com/6263244/109098133-b4900a00-775b-11eb-91ea-9c94981a02c2.png)

**Comment by lujay** [comment]
只有内部不通，从 本地去ping 这4个IP 都通， 在pg节点互ping 正常， 只有从元节点ping 不能互通，

**Comment by Vonng** [comment]
啊这。
你可能得检查一下 [连接参数](http://pigsty.cc/zh/docs/deploy/config/1-connection/) 是不是有问题？
