### ISSUE TITLE
Support pg_embedding extensions

### ISSUE THREAD

**Issue by tobiasmuehl** [Vonng/pigsty#300]
Apologies if this extension is already available.

https://github.com/neondatabase/pg_embedding, for some workloads it is more promising than pgvector

**Comment by Vonng** [comment]
Pigsty [v2.3.1](https://github.com/Vonng/pigsty/releases/tag/v2.3.1) has included pgvector v0.5, which introduces a native HNSW index support.

The performance looks impressive:

![](https://jkatz05.com/images/dbpedia-openai-1000k-angular.png)

I'd be glad to include pg_embedding as a supplement once PGDG official rpm is available.

**Comment by tobiasmuehl** [comment]
Just stumbled upon yet another extension for this: https://github.com/lanterndata/lantern

**Comment by Vonng** [comment]
Already build pg_embedding rpm and add to default repo packages:
https://github.com/Vonng/pigsty/commit/b0ec393f4833857e5384147e5ad19d2172263d1e

**Comment by Vonng** [comment]
resolved by https://github.com/Vonng/pigsty/commit/4aa22efb6b1435a43f19368d21467fc0e3cf80ea
released in v2.4.0
