### ISSUE TITLE
xpect a one-click pull from K8S+PigSty+Rook-Ceph

### ISSUE THREAD

**Issue by fi-ecavc** [Vonng/pigsty#302]
A hyper-converged pigsty must be closely related to K8S elastic applications. If you can pull up the basically usable environment with the touch of a button using SealOS or Sealer, it will make Piggsty burst! Expect a one-click pull from K8S+PigSty+Rook-Ceph.

**Comment by Vonng** [comment]
Well pigsty can do the sealos / kubernetes 1 click part. 
And I may using `pgo` for PostgreSQL cluster inside kubernetes and monitor it from prometheus outside kubernetes.
As for the rook-ceph stack, I have to look into it and compare with curve first.

**Comment by Vonng** [comment]
we already have sealos packed in Pigsty.
