### ISSUE TITLE
New Module: ELASTIC

### ISSUE THREAD

**Issue by zzzhouuu** [Vonng/pigsty#303]
Hi there,

Is there any roadmap add support for elasticsearch deployment & monitoring?

Thank you for your time and effort in maintaining this fantastic project. I look forward to your insights on this matter.

Best regards

**Comment by Vonng** [comment]
not planning, But working on introduce zhparser into PostgreSQL to support chinese zh-cn full text search.

**Comment by Vonng** [comment]
Closed because we already have ParadeDB available.
