### ISSUE TITLE
failed=1 at centos8 install.yml

### ISSUE THREAD

**Issue by resulraveendran** [Vonng/pigsty#308]
TASK [pgsql : remove postgres metadata from etcd] *********************************************************************************************************************************************************
changed: [10.10.11.195]

TASK [pgsql : remove postgres data] ***********************************************************************************************************************************************************************
ok: [10.10.11.195] => (item=/pg)
ok: [10.10.11.195] => (item=/data/postgres)
ok: [10.10.11.195] => (item=/data/backups/postgres)
ok: [10.10.11.195] => (item=/pg/log/postgres)
ok: [10.10.11.195] => (item=/pg/log/patroni)
ok: [10.10.11.195] => (item=/pg/log/pgbackrest)
ok: [10.10.11.195] => (item=/pg/log/pgbouncer)
ok: [10.10.11.195] => (item=/etc/pgbouncer)
ok: [10.10.11.195] => (item=/var/run/pgbouncer)

TASK [pgsql : create os group postgres] *******************************************************************************************************************************************************************
changed: [10.10.11.195]

TASK [pgsql : create postgres dbsu] ***********************************************************************************************************************************************************************
changed: [10.10.11.195]

TASK [pgsql : grant postgres dbsu sudo privilege] *********************************************************************************************************************************************************
changed: [10.10.11.195]

TASK [pgsql : grant postgres dbsu watchdog owner] *********************************************************************************************************************************************************
changed: [10.10.11.195]

TASK [pgsql : config postgres dbsu ssh no host checking] **************************************************************************************************************************************************
changed: [10.10.11.195]

TASK [pgsql : fetch postgres dbsu public keys] ************************************************************************************************************************************************************
changed: [10.10.11.195]

TASK [pgsql : exchange postgres dbsu ssh keys] ************************************************************************************************************************************************************
changed: [10.10.11.195] => (item=['ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDAX+25By76koW615OJkr4ai3ZvSRNlPuZz+ar4+t7K5ESYuuCBG2KLcekoNvXc7BgXiGfKLfRhASch+amRoJCasC5v0uaKhJGIWxmSQEZrM2SzirHj1LZT6dwdILH2Gmwp4PMRR21+jLCi+5OGHOOfj12GlcX/HAkoqPQcT2WAtm8G6VmdP8WXiIgCtC+tiONHEJq1s0lGFUe+j4NytMj/cS/zzPRWVxnKM/xZpmeVzmsd3FCIJFvGolS0NhiYdsRZzxMApAUYC7pRYzTH+4kVfu5rsYUaG4Y1S2JobXdO0CTZEaRw2Q4z9iIfLg8I+dX5ai75NQLqJw0BJPedSQwMuZhlsL7YKF+u+VGJEWezCUA4yNl+hLdLUG0/I0HVcTnNkxeEqouN/qJ8IDcoezaDfK11aWamfsaoGyErA+HigLyHgCtUWe7M9ojKd/wemMLA+YkZim7BtXRAH+QeXq12AQUs0WyphMZrzmSYACtkWvvd+QRPE9XisEjW4U7DSwM= ansible-generated on pg-meta-1', '10.10.11.195'])

TASK [pgsql : install postgres packages] ******************************************************************************************************************************************************************
failed: [10.10.11.195] (item=postgresql${pg_version}*) => {"ansible_loop_var": "item", "changed": false, "failures": [], "item": "postgresql${pg_version}*", "msg": "Depsolve Error occurred: \n Problem 1: cannot install both llvm-libs-15.0.7-1.module+el8.8.0+1144+0a4e73bd.x86_64 from pigsty and llvm-libs-16.0.6-3.module_el8+605+fdf31679.x86_64 from @System\n  - package postgresql15-llvmjit-15.4-1PGDG.rhel8.x86_64 from pigsty requires libLLVM-15.so()(64bit), but none of the providers can be installed\n  - package postgresql15-llvmjit-15.4-1PGDG.rhel8.x86_64 from pigsty requires libLLVM-15.so(LLVM_15)(64bit), but none of the providers can be installed\n  - package mesa-dri-drivers-23.1.4-1.el8.x86_64 from @System requires libLLVM-16.so()(64bit), but none of the providers can be installed\n  - package mesa-dri-drivers-23.1.4-1.el8.x86_64 from @System requires libLLVM-16.so(LLVM_16)(64bit), but none of the providers can be installed\n  - conflicting requests\n  - problem with installed package mesa-dri-drivers-23.1.4-1.el8.x86_64\n Problem 2: package llvm-devel-15.0.7-1.module+el8.8.0+1144+0a4e73bd.x86_64 from pigsty requires llvm-libs(x86-64) = 15.0.7-1.module+el8.8.0+1144+0a4e73bd, but none of the providers can be installed\n  - cannot install both llvm-libs-15.0.7-1.module+el8.8.0+1144+0a4e73bd.x86_64 from pigsty and llvm-libs-16.0.6-3.module_el8+605+fdf31679.x86_64 from @System\n  - package postgresql15-devel-15.4-1PGDG.rhel8.x86_64 from pigsty requires llvm-devel >= 8.0.1, but none of the providers can be installed\n  - package postgresql15-devel-15.4-1PGDG.rhel8.x86_64 from pigsty requires llvm-devel >= 13.0, but none of the providers can be installed\n  - package mesa-libxatracker-23.1.4-1.el8.x86_64 from @System requires libLLVM-16.so()(64bit), but none of the providers can be installed\n  - package mesa-libxatracker-23.1.4-1.el8.x86_64 from @System requires libLLVM-16.so(LLVM_16)(64bit), but none of the providers can be installed\n  - conflicting requests\n  - problem with installed package mesa-libxatracker-23.1.4-1.el8.x86_64\n Problem 3: package llvm-devel-15.0.7-1.module+el8.8.0+1144+0a4e73bd.x86_64 from pigsty requires llvm-libs(x86-64) = 15.0.7-1.module+el8.8.0+1144+0a4e73bd, but none of the providers can be installed\n  - cannot install both llvm-libs-15.0.7-1.module+el8.8.0+1144+0a4e73bd.x86_64 from pigsty and llvm-libs-16.0.6-3.module_el8+605+fdf31679.x86_64 from @System\n  - package postgresql15-devel-15.4-1PGDG.rhel8.x86_64 from pigsty requires llvm-devel >= 8.0.1, but none of the providers can be installed\n  - package postgresql15-devel-15.4-1PGDG.rhel8.x86_64 from pigsty requires llvm-devel >= 13.0, but none of the providers can be installed\n  - package mesa-dri-drivers-23.1.4-1.el8.x86_64 from @System requires libLLVM-16.so()(64bit), but none of the providers can be installed\n  - package mesa-dri-drivers-23.1.4-1.el8.x86_64 from @System requires libLLVM-16.so(LLVM_16)(64bit), but none of the providers can be installed\n  - package postgresql15-test-15.4-1PGDG.rhel8.x86_64 from pigsty requires postgresql15-devel(x86-64) = 15.4-1PGDG.rhel8, but none of the providers can be installed\n  - package clutter-1.26.2-8.el8.x86_64 from @System requires mesa-dri-drivers(x86-64), but none of the providers can be installed\n  - conflicting requests\n  - problem with installed package clutter-1.26.2-8.el8.x86_64", "rc": 1, "results": []}
changed: [10.10.11.195] => (item=pgbouncer pg_exporter pgbadger vip-manager patroni patroni-etcd pgbackrest)

PLAY RECAP ************************************************************************************************************************************************************************************************
10.10.11.195               : ok=205  changed=154  unreachable=0    failed=1    skipped=46   rescued=0    ignored=0   

>

**Comment by Vonng** [comment]
<https://doc.pigsty.cc/#/FAQ?id=installation>
Pigsty Docs<https://doc.pigsty.cc/#/FAQ?id=installation>
doc.pigsty.cc<https://doc.pigsty.cc/#/FAQ?id=installation>
[X]<https://doc.pigsty.cc/#/FAQ?id=installation>
Which OS version?
Maybe Check how to resolve rpm conflict .and try again later?

冯若航（Ruohang Feng）

在 2023年9月12日，15:10，resulraveendran ***@***.***> 写道：

﻿


TASK [pgsql : remove postgres metadata from etcd] *********************************************************************************************************************************************************
changed: [10.10.11.195]

TASK [pgsql : remove postgres data] ***********************************************************************************************************************************************************************
ok: [10.10.11.195] => (item=/pg)
ok: [10.10.11.195] => (item=/data/postgres)
ok: [10.10.11.195] => (item=/data/backups/postgres)
ok: [10.10.11.195] => (item=/pg/log/postgres)
ok: [10.10.11.195] => (item=/pg/log/patroni)
ok: [10.10.11.195] => (item=/pg/log/pgbackrest)
ok: [10.10.11.195] => (item=/pg/log/pgbouncer)
ok: [10.10.11.195] => (item=/etc/pgbouncer)
ok: [10.10.11.195] => (item=/var/run/pgbouncer)

TASK [pgsql : create os group postgres] *******************************************************************************************************************************************************************
changed: [10.10.11.195]

TASK [pgsql : create postgres dbsu] ***********************************************************************************************************************************************************************
changed: [10.10.11.195]

TASK [pgsql : grant postgres dbsu sudo privilege] *********************************************************************************************************************************************************
changed: [10.10.11.195]

TASK [pgsql : grant postgres dbsu watchdog owner] *********************************************************************************************************************************************************
changed: [10.10.11.195]

TASK [pgsql : config postgres dbsu ssh no host checking] **************************************************************************************************************************************************
changed: [10.10.11.195]

TASK [pgsql : fetch postgres dbsu public keys] ************************************************************************************************************************************************************
changed: [10.10.11.195]

TASK [pgsql : exchange postgres dbsu ssh keys] ************************************************************************************************************************************************************
changed: [10.10.11.195] => (item=['ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDAX+25By76koW615OJkr4ai3ZvSRNlPuZz+ar4+t7K5ESYuuCBG2KLcekoNvXc7BgXiGfKLfRhASch+amRoJCasC5v0uaKhJGIWxmSQEZrM2SzirHj1LZT6dwdILH2Gmwp4PMRR21+jLCi+5OGHOOfj12GlcX/HAkoqPQcT2WAtm8G6VmdP8WXiIgCtC+tiONHEJq1s0lGFUe+j4NytMj/cS/zzPRWVxnKM/xZpmeVzmsd3FCIJFvGolS0NhiYdsRZzxMApAUYC7pRYzTH+4kVfu5rsYUaG4Y1S2JobXdO0CTZEaRw2Q4z9iIfLg8I+dX5ai75NQLqJw0BJPedSQwMuZhlsL7YKF+u+VGJEWezCUA4yNl+hLdLUG0/I0HVcTnNkxeEqouN/qJ8IDcoezaDfK11aWamfsaoGyErA+HigLyHgCtUWe7M9ojKd/wemMLA+YkZim7BtXRAH+QeXq12AQUs0WyphMZrzmSYACtkWvvd+QRPE9XisEjW4U7DSwM= ansible-generated on pg-meta-1', '10.10.11.195'])

TASK [pgsql : install postgres packages] ******************************************************************************************************************************************************************
failed: [10.10.11.195] (item=postgresql${pg_version}*) => {"ansible_loop_var": "item", "changed": false, "failures": [], "item": "postgresql${pg_version}*", "msg": "Depsolve Error occurred: \n Problem 1: cannot install both llvm-libs-15.0.7-1.module+el8.8.0+1144+0a4e73bd.x86_64 from pigsty and llvm-libs-16.0.6-3.module_el8+605+fdf31679.x86_64 from @System\n  - package postgresql15-llvmjit-15.4-1PGDG.rhel8.x86_64 from pigsty requires libLLVM-15.so()(64bit), but none of the providers can be installed\n  - package postgresql15-llvmjit-15.4-1PGDG.rhel8.x86_64 from pigsty requires libLLVM-15.so(LLVM_15)(64bit), but none of the providers can be installed\n  - package mesa-dri-drivers-23.1.4-1.el8.x86_64 from @System requires libLLVM-16.so()(64bit), but none of the providers can be installed\n  - package mesa-dri-drivers-23.1.4-1.el8.x86_64 from @System requires libLLVM-16.so(LLVM_16)(64bit), but none of the providers can be installed\n  - conflicting requests\n  - problem with installed package mesa-dri-drivers-23.1.4-1.el8.x86_64\n Problem 2: package llvm-devel-15.0.7-1.module+el8.8.0+1144+0a4e73bd.x86_64 from pigsty requires llvm-libs(x86-64) = 15.0.7-1.module+el8.8.0+1144+0a4e73bd, but none of the providers can be installed\n  - cannot install both llvm-libs-15.0.7-1.module+el8.8.0+1144+0a4e73bd.x86_64 from pigsty and llvm-libs-16.0.6-3.module_el8+605+fdf31679.x86_64 from @System\n  - package postgresql15-devel-15.4-1PGDG.rhel8.x86_64 from pigsty requires llvm-devel >= 8.0.1, but none of the providers can be installed\n  - package postgresql15-devel-15.4-1PGDG.rhel8.x86_64 from pigsty requires llvm-devel >= 13.0, but none of the providers can be installed\n  - package mesa-libxatracker-23.1.4-1.el8.x86_64 from @System requires libLLVM-16.so()(64bit), but none of the providers can be installed\n  - package mesa-libxatracker-23.1.4-1.el8.x86_64 from @System requires libLLVM-16.so(LLVM_16)(64bit), but none of the providers can be installed\n  - conflicting requests\n  - problem with installed package mesa-libxatracker-23.1.4-1.el8.x86_64\n Problem 3: package llvm-devel-15.0.7-1.module+el8.8.0+1144+0a4e73bd.x86_64 from pigsty requires llvm-libs(x86-64) = 15.0.7-1.module+el8.8.0+1144+0a4e73bd, but none of the providers can be installed\n  - cannot install both llvm-libs-15.0.7-1.module+el8.8.0+1144+0a4e73bd.x86_64 from pigsty and llvm-libs-16.0.6-3.module_el8+605+fdf31679.x86_64 from @System\n  - package postgresql15-devel-15.4-1PGDG.rhel8.x86_64 from pigsty requires llvm-devel >= 8.0.1, but none of the providers can be installed\n  - package postgresql15-devel-15.4-1PGDG.rhel8.x86_64 from pigsty requires llvm-devel >= 13.0, but none of the providers can be installed\n  - package mesa-dri-drivers-23.1.4-1.el8.x86_64 from @System requires libLLVM-16.so()(64bit), but none of the providers can be installed\n  - package mesa-dri-drivers-23.1.4-1.el8.x86_64 from @System requires libLLVM-16.so(LLVM_16)(64bit), but none of the providers can be installed\n  - package postgresql15-test-15.4-1PGDG.rhel8.x86_64 from pigsty requires postgresql15-devel(x86-64) = 15.4-1PGDG.rhel8, but none of the providers can be installed\n  - package clutter-1.26.2-8.el8.x86_64 from @System requires mesa-dri-drivers(x86-64), but none of the providers can be installed\n  - conflicting requests\n  - problem with installed package clutter-1.26.2-8.el8.x86_64", "rc": 1, "results": []}
changed: [10.10.11.195] => (item=pgbouncer pg_exporter pgbadger vip-manager patroni patroni-etcd pgbackrest)

PLAY RECAP ************************************************************************************************************************************************************************************************
10.10.11.195               : ok=205  changed=154  unreachable=0    failed=1    skipped=46   rescued=0    ignored=0

**Comment by Vonng** [comment]
Pre-packed RPM conflict can be resolved by:

https://doc.pigsty.cc/#/FAQ?id=installation

If you are not using the exact EL release 9.1 8.7 7.9, There may have a slight chance that rpm conflict occurs during node/infra/pgsql packages installation.

The simplest way to resolve this is to install without offline packages, which will download directly from the upstream repo.

If there are only a few problematic RPMs, you can use a trick to fix the yum repo quickly:

```bash
rm -rf /www/pigsty/repo_complete    # delete the repo_complete flag file to mark this repo incomplete
rm -rf SomeBrokenRPMPackages        # delete problematic RPMs
./infra.yml -t repo_upstream        # write upstream repos. you can also use /etc/yum.repos.d/backup/*
./infra.yml -t repo_pkg             # download rpms according to your current OS
```

Besides, if not resolved, consider add distribution adhoc repo to `repo_upstream`: https://download.postgresql.org/pub/repos/yum/common/
