### ISSUE TITLE
Got this issue run Install.yml in CentOS Stream release 8

### ISSUE THREAD

**Issue by resulraveendran** [Vonng/pigsty#309]
failed: [10.10.11.195] (item=postgresql${pg_version}*) => {"ansible_loop_var": "item", "changed": false, "failures": [], "item": "postgresql${pg_version}*", "msg": "Depsolve Error occurred: \n Problem: package gcc-c++-8.5.0-18.el8.x86_64 from pigsty requires gcc = 8.5.0-18.el8, but none of the providers can be installed\n  - package gcc-8.5.0-18.el8.x86_64 from pigsty requires glibc-devel >= 2.2.90-12, but none of the providers can be installed\n  - package clang-15.0.7-1.module+el8.8.0+1144+0a4e73bd.x86_64 from pigsty requires gcc-c++, but none of the providers can be installed\n  - package glibc-devel-2.28-225.el8.x86_64 from pigsty requires glibc = 2.28-225.el8, but none of the providers can be installed\n  - package clang-devel-15.0.7-1.module+el8.8.0+1144+0a4e73bd.x86_64 from pigsty requires clang(x86-64) = 15.0.7-1.module+el8.8.0+1144+0a4e73bd, but none of the providers can be installed\n  - cannot install both glibc-2.28-225.el8.x86_64 from pigsty and glibc-2.28-236.el8.x86_64 from @System\n  - package postgresql15-devel-15.4-1PGDG.rhel8.x86_64 from pigsty requires clang-devel >= 8.0.1, but none of the providers can be installed\n  - package postgresql15-devel-15.4-1PGDG.rhel8.x86_64 from pigsty requires clang-devel >= 13.0, but none of the providers can be installed\n  - package glibc-langpack-en-2.28-236.el8.x86_64 from @System requires glibc = 2.28-236.el8, but none of the providers can be installed\n  - conflicting requests\n  - problem with installed package glibc-langpack-en-2.28-236.el8.x86_64", "rc": 1, "results": []}

**Comment by Vonng** [comment]
Check [FAQ](https://doc.pigsty.cc/#/FAQ?id=installation) to resolve RPM conflict.

**Comment by wishfay** [comment]
It seems that there is still some RPM conflict when i execute `./install.yml` even if i use rockyLinux8.9 which is recommended. That's make pigsty2.7 hard to deploy offline.

Follow [https://doc.pigsty.cc/#/FAQ?id=installation](url) seems still cannot help to solve RPM conflict problem, however, is there some easier solution for totally offline environment?

Here's the cmd history:
``` bash
[root@localhost pigsty]# ./bootstrap 
bootstrap pigsty v2.7.0 begin
[ OK ] region = china
[ OK ] kernel = Linux
[ OK ] machine = x86_64
[ OK ] package = rpm,dnf
[ OK ] vendor = rocky (Rocky Linux)
[ OK ] version = 8 (8.9)
[ OK ] sudo = root ok
[ OK ] cache = /tmp/pkg.tgz exists
[ OK ] repo = extract from /tmp/pkg.tgz
[ OK ] repo file = use /etc/yum.repos.d/pigsty-local.repo
[WARN] rpm cache = updating, make take a while
[ OK ] repo cache = created
[ OK ] install el8 utils

[root@localhost pigsty]# ./configure
configure pigsty v2.7.0 begin
[ OK ] region = china
[ OK ] kernel = Linux
[ OK ] machine = x86_64
[ OK ] package = rpm,dnf
[ OK ] vendor = rocky (Rocky Linux)
[ OK ] version = 8 (8.9)
[ OK ] sudo = root ok
[WARN] ssh = root@127.0.0.1 fixed
[WARN] Multiple IP address candidates found:
    (1) 192.168.14.133	    inet 192.168.14.133/24 brd 192.168.14.255 scope global dynamic noprefixroute ens33
    (2) 192.168.122.1	    inet 192.168.122.1/24 brd 192.168.122.255 scope global virbr0
[ IN ] INPUT primary_ip address (of current meta node, e.g 10.10.10.10):
=> 192.168.14.133
[ OK ] primary_ip = 192.168.14.133 (from input)
[ OK ] admin = root@192.168.14.133 ok
[WARN] use root = not recommended, are you sure?
[ OK ] config = el8 @ 192.168.14.133
[ OK ] configure pigsty done

[root@localhost pigsty]# ./install.yml 
...
TASK [pgsql : install postgres packages] ***************************************************************************
failed: [192.168.14.133] (item=postgresql$v*) => {"ansible_loop_var": "item", "changed": false, "failures": [], "item": "postgresql$v*", "msg": "Depsolve Error occurred: \n Problem 1: package gcc-c++-8.5.0-20.el8.x86_64 from pigsty-local requires gcc = 8.5.0-20.el8, but none of the providers can be installed\n  - package gcc-8.5.0-20.el8.x86_64 from pigsty-local requires glibc-devel >= 2.2.90-12, but none of the providers can be installed\n  - package clang-16.0.6-2.module+el8.9.0+1651+e10a8f6d.x86_64 from pigsty-local requires gcc-c++, but none of the providers can be installed\n  - package glibc-devel-2.28-236.el8_9.13.x86_64 from pigsty-local requires glibc = 2.28-236.el8_9.13, but none of the providers can be installed\n  - package clang-devel-16.0.6-2.module+el8.9.0+1651+e10a8f6d.x86_64 from pigsty-local requires clang(x86-64) = 16.0.6-2.module+el8.9.0+1651+e10a8f6d, but none of the providers can be installed\n  - cannot install both glibc-2.28-236.el8_9.13.x86_64 from pigsty-local and glibc-2.28-236.el8_9.7.x86_64 from @System\n  - package postgresql16-devel-16.3-1PGDG.rhel8.x86_64 from pigsty-local requires clang-devel >= 8.0.1, but none of the providers can be installed\n  - package glibc-langpack-en-2.28-236.el8_9.7.x86_64 from @System requires glibc = 2.28-236.el8_9.7, but none of the providers can be installed\n  - conflicting requests\n  - problem with installed package glibc-langpack-en-2.28-236.el8_9.7.x86_64\n Problem 2: package gcc-c++-8.5.0-20.el8.x86_64 from pigsty-local requires gcc = 8.5.0-20.el8, but none of the providers can be installed\n  - package gcc-8.5.0-20.el8.x86_64 from pigsty-local requires glibc-devel >= 2.2.90-12, but none of the providers can be installed\n  - package clang-16.0.6-2.module+el8.9.0+1651+e10a8f6d.x86_64 from pigsty-local requires gcc-c++, but none of the providers can be installed\n  - package glibc-devel-2.28-236.el8_9.13.x86_64 from pigsty-local requires glibc = 2.28-236.el8_9.13, but none of the providers can be installed\n  - package clang-devel-16.0.6-2.module+el8.9.0+1651+e10a8f6d.x86_64 from pigsty-local requires clang(x86-64) = 16.0.6-2.module+el8.9.0+1651+e10a8f6d, but none of the providers can be installed\n  - cannot install both glibc-2.28-236.el8_9.13.x86_64 from pigsty-local and glibc-2.28-236.el8_9.7.x86_64 from @System\n  - package postgresql16-devel-16.3-1PGDG.rhel8.x86_64 from pigsty-local requires clang-devel >= 8.0.1, but none of the providers can be installed\n  - package glibc-langpack-en-2.28-236.el8_9.7.x86_64 from @System requires glibc = 2.28-236.el8_9.7, but none of the providers can be installed\n  - package postgresql16-test-16.3-1PGDG.rhel8.x86_64 from pigsty-local requires postgresql16-devel(x86-64) = 16.3-1PGDG.rhel8, but none of the providers can be installed\n  - package anaconda-core-33.16.9.4-1.el8.rocky.0.1.x86_64 from @System requires glibc-langpack-en, but none of the providers can be installed\n  - conflicting requests\n  - problem with installed package anaconda-core-33.16.9.4-1.el8.rocky.0.1.x86_64", "rc": 1, "results": []}
...
```
Follow FAQ:
``` bash
rm -rf /www/pigsty/repo_complete    
./infra.yml -t repo_upstream    
./infra.yml -t repo_pkg         
```
Then ./install.yml, seems that it still has problem:
``` bash
TASK [pgsql : install postgres packages] ***************************************************************************
failed: [192.168.14.133] (item=postgresql$v*) => {"ansible_loop_var": "item", "changed": false, "failures": [], "item": "postgresql$v*", "msg": "Depsolve Error occurred: \n Problem 1: package mesa-libxatracker-23.1.4-1.el8.x86_64 from @System requires libLLVM-16.so()(64bit), but none of the providers can be installed\n  - package mesa-libxatracker-23.1.4-1.el8.x86_64 from @System requires libLLVM-16.so(LLVM_16)(64bit), but none of the providers can be installed\n  - cannot install both llvm-libs-17.0.6-2.module+el8.10.0+1694+aabef26e.x86_64 from pigsty-local and llvm-libs-16.0.6-3.module+el8.9.0+1651+e10a8f6d.x86_64 from @System\n  - cannot install both llvm-libs-17.0.6-2.module+el8.10.0+1694+aabef26e.x86_64 from pigsty-local and llvm-libs-16.0.6-3.module+el8.9.0+1651+e10a8f6d.x86_64 from pigsty-local\n  - package postgresql16-llvmjit-16.3-3PGDG.rhel8.x86_64 from pigsty-local requires libLLVM-17.so()(64bit), but none of the providers can be installed\n  - package postgresql16-llvmjit-16.3-3PGDG.rhel8.x86_64 from pigsty-local requires libLLVM-17.so(LLVM_17)(64bit), but none of the providers can be installed\n  - cannot install the best candidate for the job\n  - problem with installed package mesa-libxatracker-23.1.4-1.el8.x86_64\n Problem 2: package postgresql16-devel-16.3-3PGDG.rhel8.x86_64 from pigsty-local requires clang-devel >= 8.0.1, but none of the providers can be installed\n  - package clang-devel-16.0.6-2.module+el8.9.0+1651+e10a8f6d.x86_64 from pigsty-local requires libclang-cpp.so.16()(64bit), but none of the providers can be installed\n  - package clang-devel-16.0.6-2.module+el8.9.0+1651+e10a8f6d.x86_64 from pigsty-local requires libclang.so.16()(64bit), but none of the providers can be installed\n  - package clang-devel-16.0.6-2.module+el8.9.0+1651+e10a8f6d.x86_64 from pigsty-local requires clang-libs = 16.0.6-2.module+el8.9.0+1651+e10a8f6d, but none of the providers can be installed\n  - package clang-devel-17.0.6-1.module+el8.10.0+1595+29ffb9b1.x86_64 from pigsty-local requires libclang-cpp.so.17()(64bit), but none of the providers can be installed\n  - package clang-devel-17.0.6-1.module+el8.10.0+1595+29ffb9b1.x86_64 from pigsty-local requires libclang.so.17()(64bit), but none of the providers can be installed\n  - package clang-devel-17.0.6-1.module+el8.10.0+1595+29ffb9b1.x86_64 from pigsty-local requires clang-libs = 17.0.6-1.module+el8.10.0+1595+29ffb9b1, but none of the providers can be installed\n  - package clang-libs-16.0.6-2.module+el8.9.0+1651+e10a8f6d.x86_64 from pigsty-local requires gcc-toolset-13-gcc-c++, but none of the providers can be installed\n  - package clang-libs-17.0.6-1.module+el8.10.0+1595+29ffb9b1.x86_64 from pigsty-local requires gcc-toolset-13-gcc-c++, but none of the providers can be installed\n  - package gcc-toolset-13-gcc-c++-13.1.1-4.3.el8.x86_64 from pigsty-local requires gcc-toolset-13-gcc = 13.1.1-4.3.el8, but none of the providers can be installed\n  - package gcc-toolset-13-gcc-c++-13.2.1-6.2.el8.x86_64 from pigsty-local requires gcc-toolset-13-gcc = 13.2.1-6.2.el8, but none of the providers can be installed\n  - package gcc-toolset-13-gcc-13.1.1-4.3.el8.x86_64 from pigsty-local requires glibc-devel >= 2.2.90-12, but none of the providers can be installed\n  - package gcc-toolset-13-gcc-13.2.1-6.2.el8.x86_64 from pigsty-local requires glibc-devel >= 2.2.90-12, but none of the providers can be installed\n  - package glibc-devel-2.28-236.el8_9.13.x86_64 from pigsty-local requires glibc = 2.28-236.el8_9.13, but none of the providers can be installed\n  - package glibc-devel-2.28-251.el8_10.2.x86_64 from pigsty-local requires glibc = 2.28-251.el8_10.2, but none of the providers can be installed\n  - cannot install both glibc-2.28-236.el8_9.13.x86_64 from pigsty-local and glibc-2.28-236.el8_9.7.x86_64 from @System\n  - cannot install both glibc-2.28-251.el8_10.2.x86_64 from pigsty-local and glibc-2.28-236.el8_9.7.x86_64 from @System\n  - package glibc-langpack-en-2.28-236.el8_9.7.x86_64 from @System requires glibc = 2.28-236.el8_9.7, but none of the providers can be installed\n  - cannot install the best candidate for the job\n  - problem with installed package glibc-langpack-en-2.28-236.el8_9.7.x86_64\n Problem 3: package postgresql16-devel-16.3-3PGDG.rhel8.x86_64 from pigsty-local requires clang-devel >= 8.0.1, but none of the providers can be installed\n  - package clang-devel-16.0.6-2.module+el8.9.0+1651+e10a8f6d.x86_64 from pigsty-local requires libclang-cpp.so.16()(64bit), but none of the providers can be installed\n  - package clang-devel-16.0.6-2.module+el8.9.0+1651+e10a8f6d.x86_64 from pigsty-local requires libclang.so.16()(64bit), but none of the providers can be installed\n  - package clang-devel-16.0.6-2.module+el8.9.0+1651+e10a8f6d.x86_64 from pigsty-local requires clang-libs = 16.0.6-2.module+el8.9.0+1651+e10a8f6d, but none of the providers can be installed\n  - package clang-devel-17.0.6-1.module+el8.10.0+1595+29ffb9b1.x86_64 from pigsty-local requires libclang-cpp.so.17()(64bit), but none of the providers can be installed\n  - package clang-devel-17.0.6-1.module+el8.10.0+1595+29ffb9b1.x86_64 from pigsty-local requires libclang.so.17()(64bit), but none of the providers can be installed\n  - package clang-devel-17.0.6-1.module+el8.10.0+1595+29ffb9b1.x86_64 from pigsty-local requires clang-libs = 17.0.6-1.module+el8.10.0+1595+29ffb9b1, but none of the providers can be installed\n  - package clang-libs-16.0.6-2.module+el8.9.0+1651+e10a8f6d.x86_64 from pigsty-local requires gcc-toolset-13-gcc-c++, but none of the providers can be installed\n  - package clang-libs-17.0.6-1.module+el8.10.0+1595+29ffb9b1.x86_64 from pigsty-local requires gcc-toolset-13-gcc-c++, but none of the providers can be installed\n  - package gcc-toolset-13-gcc-c++-13.1.1-4.3.el8.x86_64 from pigsty-local requires gcc-toolset-13-gcc = 13.1.1-4.3.el8, but none of the providers can be installed\n  - package gcc-toolset-13-gcc-c++-13.2.1-6.2.el8.x86_64 from pigsty-local requires gcc-toolset-13-gcc = 13.2.1-6.2.el8, but none of the providers can be installed\n  - package gcc-toolset-13-gcc-13.1.1-4.3.el8.x86_64 from pigsty-local requires glibc-devel >= 2.2.90-12, but none of the providers can be installed\n  - package gcc-toolset-13-gcc-13.2.1-6.2.el8.x86_64 from pigsty-local requires glibc-devel >= 2.2.90-12, but none of the providers can be installed\n  - package glibc-devel-2.28-236.el8_9.13.x86_64 from pigsty-local requires glibc = 2.28-236.el8_9.13, but none of the providers can be installed\n  - package glibc-devel-2.28-251.el8_10.2.x86_64 from pigsty-local requires glibc = 2.28-251.el8_10.2, but none of the providers can be installed\n  - cannot install both glibc-2.28-236.el8_9.13.x86_64 from pigsty-local and glibc-2.28-236.el8_9.7.x86_64 from @System\n  - cannot install both glibc-2.28-251.el8_10.2.x86_64 from pigsty-local and glibc-2.28-236.el8_9.7.x86_64 from @System\n  - package glibc-langpack-en-2.28-236.el8_9.7.x86_64 from @System requires glibc = 2.28-236.el8_9.7, but none of the providers can be installed\n  - package postgresql16-test-16.3-3PGDG.rhel8.x86_64 from pigsty-local requires postgresql16-devel(x86-64) = 16.3-3PGDG.rhel8, but none of the providers can be installed\n  - package anaconda-core-33.16.9.4-1.el8.rocky.0.1.x86_64 from @System requires glibc-langpack-en, but none of the providers can be installed\n  - cannot install the best candidate for the job\n  - problem with installed package anaconda-core-33.16.9.4-1.el8.rocky.0.1.x86_64", "rc": 1, "results": []}
```

**Comment by Vonng** [comment]
> It seems that there is still some RPM conflict when i execute `./install.yml` even if i use rockyLinux8.9 which is recommended. That's make pigsty2.7 hard to deploy offline.
> 
> Follow [https://doc.pigsty.cc/#/FAQ?id=installation](url) seems still cannot help to solve RPM conflict problem, however, is there some easier solution for totally offline environment?
> 
> Here's the cmd history:
> 
> ```shell
> [root@localhost pigsty]# ./bootstrap 
> bootstrap pigsty v2.7.0 begin
> [ OK ] region = china
> [ OK ] kernel = Linux
> [ OK ] machine = x86_64
> [ OK ] package = rpm,dnf
> [ OK ] vendor = rocky (Rocky Linux)
> [ OK ] version = 8 (8.9)
> [ OK ] sudo = root ok
> [ OK ] cache = /tmp/pkg.tgz exists
> [ OK ] repo = extract from /tmp/pkg.tgz
> [ OK ] repo file = use /etc/yum.repos.d/pigsty-local.repo
> [WARN] rpm cache = updating, make take a while
> [ OK ] repo cache = created
> [ OK ] install el8 utils
> 
> [root@localhost pigsty]# ./configure
> configure pigsty v2.7.0 begin
> [ OK ] region = china
> [ OK ] kernel = Linux
> [ OK ] machine = x86_64
> [ OK ] package = rpm,dnf
> [ OK ] vendor = rocky (Rocky Linux)
> [ OK ] version = 8 (8.9)
> [ OK ] sudo = root ok
> [WARN] ssh = root@127.0.0.1 fixed
> [WARN] Multiple IP address candidates found:
>     (1) 192.168.14.133	    inet 192.168.14.133/24 brd 192.168.14.255 scope global dynamic noprefixroute ens33
>     (2) 192.168.122.1	    inet 192.168.122.1/24 brd 192.168.122.255 scope global virbr0
> [ IN ] INPUT primary_ip address (of current meta node, e.g 10.10.10.10):
> => 192.168.14.133
> [ OK ] primary_ip = 192.168.14.133 (from input)
> [ OK ] admin = root@192.168.14.133 ok
> [WARN] use root = not recommended, are you sure?
> [ OK ] config = el8 @ 192.168.14.133
> [ OK ] configure pigsty done
> 
> [root@localhost pigsty]# ./install.yml 
> ...
> TASK [pgsql : install postgres packages] ***************************************************************************
> failed: [192.168.14.133] (item=postgresql$v*) => {"ansible_loop_var": "item", "changed": false, "failures": [], "item": "postgresql$v*", "msg": "Depsolve Error occurred: \n Problem 1: package gcc-c++-8.5.0-20.el8.x86_64 from pigsty-local requires gcc = 8.5.0-20.el8, but none of the providers can be installed\n  - package gcc-8.5.0-20.el8.x86_64 from pigsty-local requires glibc-devel >= 2.2.90-12, but none of the providers can be installed\n  - package clang-16.0.6-2.module+el8.9.0+1651+e10a8f6d.x86_64 from pigsty-local requires gcc-c++, but none of the providers can be installed\n  - package glibc-devel-2.28-236.el8_9.13.x86_64 from pigsty-local requires glibc = 2.28-236.el8_9.13, but none of the providers can be installed\n  - package clang-devel-16.0.6-2.module+el8.9.0+1651+e10a8f6d.x86_64 from pigsty-local requires clang(x86-64) = 16.0.6-2.module+el8.9.0+1651+e10a8f6d, but none of the providers can be installed\n  - cannot install both glibc-2.28-236.el8_9.13.x86_64 from pigsty-local and glibc-2.28-236.el8_9.7.x86_64 from @System\n  - package postgresql16-devel-16.3-1PGDG.rhel8.x86_64 from pigsty-local requires clang-devel >= 8.0.1, but none of the providers can be installed\n  - package glibc-langpack-en-2.28-236.el8_9.7.x86_64 from @System requires glibc = 2.28-236.el8_9.7, but none of the providers can be installed\n  - conflicting requests\n  - problem with installed package glibc-langpack-en-2.28-236.el8_9.7.x86_64\n Problem 2: package gcc-c++-8.5.0-20.el8.x86_64 from pigsty-local requires gcc = 8.5.0-20.el8, but none of the providers can be installed\n  - package gcc-8.5.0-20.el8.x86_64 from pigsty-local requires glibc-devel >= 2.2.90-12, but none of the providers can be installed\n  - package clang-16.0.6-2.module+el8.9.0+1651+e10a8f6d.x86_64 from pigsty-local requires gcc-c++, but none of the providers can be installed\n  - package glibc-devel-2.28-236.el8_9.13.x86_64 from pigsty-local requires glibc = 2.28-236.el8_9.13, but none of the providers can be installed\n  - package clang-devel-16.0.6-2.module+el8.9.0+1651+e10a8f6d.x86_64 from pigsty-local requires clang(x86-64) = 16.0.6-2.module+el8.9.0+1651+e10a8f6d, but none of the providers can be installed\n  - cannot install both glibc-2.28-236.el8_9.13.x86_64 from pigsty-local and glibc-2.28-236.el8_9.7.x86_64 from @System\n  - package postgresql16-devel-16.3-1PGDG.rhel8.x86_64 from pigsty-local requires clang-devel >= 8.0.1, but none of the providers can be installed\n  - package glibc-langpack-en-2.28-236.el8_9.7.x86_64 from @System requires glibc = 2.28-236.el8_9.7, but none of the providers can be installed\n  - package postgresql16-test-16.3-1PGDG.rhel8.x86_64 from pigsty-local requires postgresql16-devel(x86-64) = 16.3-1PGDG.rhel8, but none of the providers can be installed\n  - package anaconda-core-33.16.9.4-1.el8.rocky.0.1.x86_64 from @System requires glibc-langpack-en, but none of the providers can be installed\n  - conflicting requests\n  - problem with installed package anaconda-core-33.16.9.4-1.el8.rocky.0.1.x86_64", "rc": 1, "results": []}
> ...
> ```
> 
> Follow FAQ:
> 
> ```shell
> rm -rf /www/pigsty/repo_complete    
> ./infra.yml -t repo_upstream    
> ./infra.yml -t repo_pkg         
> ```
> 
> Then ./install.yml, seems that it still has problem:
> 
> ```shell
> TASK [pgsql : install postgres packages] ***************************************************************************
> failed: [192.168.14.133] (item=postgresql$v*) => {"ansible_loop_var": "item", "changed": false, "failures": [], "item": "postgresql$v*", "msg": "Depsolve Error occurred: \n Problem 1: package mesa-libxatracker-23.1.4-1.el8.x86_64 from @System requires libLLVM-16.so()(64bit), but none of the providers can be installed\n  - package mesa-libxatracker-23.1.4-1.el8.x86_64 from @System requires libLLVM-16.so(LLVM_16)(64bit), but none of the providers can be installed\n  - cannot install both llvm-libs-17.0.6-2.module+el8.10.0+1694+aabef26e.x86_64 from pigsty-local and llvm-libs-16.0.6-3.module+el8.9.0+1651+e10a8f6d.x86_64 from @System\n  - cannot install both llvm-libs-17.0.6-2.module+el8.10.0+1694+aabef26e.x86_64 from pigsty-local and llvm-libs-16.0.6-3.module+el8.9.0+1651+e10a8f6d.x86_64 from pigsty-local\n  - package postgresql16-llvmjit-16.3-3PGDG.rhel8.x86_64 from pigsty-local requires libLLVM-17.so()(64bit), but none of the providers can be installed\n  - package postgresql16-llvmjit-16.3-3PGDG.rhel8.x86_64 from pigsty-local requires libLLVM-17.so(LLVM_17)(64bit), but none of the providers can be installed\n  - cannot install the best candidate for the job\n  - problem with installed package mesa-libxatracker-23.1.4-1.el8.x86_64\n Problem 2: package postgresql16-devel-16.3-3PGDG.rhel8.x86_64 from pigsty-local requires clang-devel >= 8.0.1, but none of the providers can be installed\n  - package clang-devel-16.0.6-2.module+el8.9.0+1651+e10a8f6d.x86_64 from pigsty-local requires libclang-cpp.so.16()(64bit), but none of the providers can be installed\n  - package clang-devel-16.0.6-2.module+el8.9.0+1651+e10a8f6d.x86_64 from pigsty-local requires libclang.so.16()(64bit), but none of the providers can be installed\n  - package clang-devel-16.0.6-2.module+el8.9.0+1651+e10a8f6d.x86_64 from pigsty-local requires clang-libs = 16.0.6-2.module+el8.9.0+1651+e10a8f6d, but none of the providers can be installed\n  - package clang-devel-17.0.6-1.module+el8.10.0+1595+29ffb9b1.x86_64 from pigsty-local requires libclang-cpp.so.17()(64bit), but none of the providers can be installed\n  - package clang-devel-17.0.6-1.module+el8.10.0+1595+29ffb9b1.x86_64 from pigsty-local requires libclang.so.17()(64bit), but none of the providers can be installed\n  - package clang-devel-17.0.6-1.module+el8.10.0+1595+29ffb9b1.x86_64 from pigsty-local requires clang-libs = 17.0.6-1.module+el8.10.0+1595+29ffb9b1, but none of the providers can be installed\n  - package clang-libs-16.0.6-2.module+el8.9.0+1651+e10a8f6d.x86_64 from pigsty-local requires gcc-toolset-13-gcc-c++, but none of the providers can be installed\n  - package clang-libs-17.0.6-1.module+el8.10.0+1595+29ffb9b1.x86_64 from pigsty-local requires gcc-toolset-13-gcc-c++, but none of the providers can be installed\n  - package gcc-toolset-13-gcc-c++-13.1.1-4.3.el8.x86_64 from pigsty-local requires gcc-toolset-13-gcc = 13.1.1-4.3.el8, but none of the providers can be installed\n  - package gcc-toolset-13-gcc-c++-13.2.1-6.2.el8.x86_64 from pigsty-local requires gcc-toolset-13-gcc = 13.2.1-6.2.el8, but none of the providers can be installed\n  - package gcc-toolset-13-gcc-13.1.1-4.3.el8.x86_64 from pigsty-local requires glibc-devel >= 2.2.90-12, but none of the providers can be installed\n  - package gcc-toolset-13-gcc-13.2.1-6.2.el8.x86_64 from pigsty-local requires glibc-devel >= 2.2.90-12, but none of the providers can be installed\n  - package glibc-devel-2.28-236.el8_9.13.x86_64 from pigsty-local requires glibc = 2.28-236.el8_9.13, but none of the providers can be installed\n  - package glibc-devel-2.28-251.el8_10.2.x86_64 from pigsty-local requires glibc = 2.28-251.el8_10.2, but none of the providers can be installed\n  - cannot install both glibc-2.28-236.el8_9.13.x86_64 from pigsty-local and glibc-2.28-236.el8_9.7.x86_64 from @System\n  - cannot install both glibc-2.28-251.el8_10.2.x86_64 from pigsty-local and glibc-2.28-236.el8_9.7.x86_64 from @System\n  - package glibc-langpack-en-2.28-236.el8_9.7.x86_64 from @System requires glibc = 2.28-236.el8_9.7, but none of the providers can be installed\n  - cannot install the best candidate for the job\n  - problem with installed package glibc-langpack-en-2.28-236.el8_9.7.x86_64\n Problem 3: package postgresql16-devel-16.3-3PGDG.rhel8.x86_64 from pigsty-local requires clang-devel >= 8.0.1, but none of the providers can be installed\n  - package clang-devel-16.0.6-2.module+el8.9.0+1651+e10a8f6d.x86_64 from pigsty-local requires libclang-cpp.so.16()(64bit), but none of the providers can be installed\n  - package clang-devel-16.0.6-2.module+el8.9.0+1651+e10a8f6d.x86_64 from pigsty-local requires libclang.so.16()(64bit), but none of the providers can be installed\n  - package clang-devel-16.0.6-2.module+el8.9.0+1651+e10a8f6d.x86_64 from pigsty-local requires clang-libs = 16.0.6-2.module+el8.9.0+1651+e10a8f6d, but none of the providers can be installed\n  - package clang-devel-17.0.6-1.module+el8.10.0+1595+29ffb9b1.x86_64 from pigsty-local requires libclang-cpp.so.17()(64bit), but none of the providers can be installed\n  - package clang-devel-17.0.6-1.module+el8.10.0+1595+29ffb9b1.x86_64 from pigsty-local requires libclang.so.17()(64bit), but none of the providers can be installed\n  - package clang-devel-17.0.6-1.module+el8.10.0+1595+29ffb9b1.x86_64 from pigsty-local requires clang-libs = 17.0.6-1.module+el8.10.0+1595+29ffb9b1, but none of the providers can be installed\n  - package clang-libs-16.0.6-2.module+el8.9.0+1651+e10a8f6d.x86_64 from pigsty-local requires gcc-toolset-13-gcc-c++, but none of the providers can be installed\n  - package clang-libs-17.0.6-1.module+el8.10.0+1595+29ffb9b1.x86_64 from pigsty-local requires gcc-toolset-13-gcc-c++, but none of the providers can be installed\n  - package gcc-toolset-13-gcc-c++-13.1.1-4.3.el8.x86_64 from pigsty-local requires gcc-toolset-13-gcc = 13.1.1-4.3.el8, but none of the providers can be installed\n  - package gcc-toolset-13-gcc-c++-13.2.1-6.2.el8.x86_64 from pigsty-local requires gcc-toolset-13-gcc = 13.2.1-6.2.el8, but none of the providers can be installed\n  - package gcc-toolset-13-gcc-13.1.1-4.3.el8.x86_64 from pigsty-local requires glibc-devel >= 2.2.90-12, but none of the providers can be installed\n  - package gcc-toolset-13-gcc-13.2.1-6.2.el8.x86_64 from pigsty-local requires glibc-devel >= 2.2.90-12, but none of the providers can be installed\n  - package glibc-devel-2.28-236.el8_9.13.x86_64 from pigsty-local requires glibc = 2.28-236.el8_9.13, but none of the providers can be installed\n  - package glibc-devel-2.28-251.el8_10.2.x86_64 from pigsty-local requires glibc = 2.28-251.el8_10.2, but none of the providers can be installed\n  - cannot install both glibc-2.28-236.el8_9.13.x86_64 from pigsty-local and glibc-2.28-236.el8_9.7.x86_64 from @System\n  - cannot install both glibc-2.28-251.el8_10.2.x86_64 from pigsty-local and glibc-2.28-236.el8_9.7.x86_64 from @System\n  - package glibc-langpack-en-2.28-236.el8_9.7.x86_64 from @System requires glibc = 2.28-236.el8_9.7, but none of the providers can be installed\n  - package postgresql16-test-16.3-3PGDG.rhel8.x86_64 from pigsty-local requires postgresql16-devel(x86-64) = 16.3-3PGDG.rhel8, but none of the providers can be installed\n  - package anaconda-core-33.16.9.4-1.el8.rocky.0.1.x86_64 from @System requires glibc-langpack-en, but none of the providers can be installed\n  - cannot install the best candidate for the job\n  - problem with installed package anaconda-core-33.16.9.4-1.el8.rocky.0.1.x86_64", "rc": 1, "results": []}
> ```



The issue is that upstream repo will update package version periodally, and sometimes breaks the dependencies:

To ensure a success installation, consider using an [offline installation](https://pigsty.io/docs/setup/offline/), which pack all the deps snapshot in that certain moment.
