### ISSUE TITLE
PostgreSQL Extensions

### ISSUE THREAD

**Issue by Vonng** [Vonng/pigsty#311]
Pigsty now has an official Yum repo: https://repo.pigsty.cc/rpm , including some PostgreSQL extension RPMs for EL7 - EL9 missing in the PGDG repo.

| name                         | version |   source   | type  | comment                                                                                                                    |
|------------------------------|:-------:|:----------:|:-----:|----------------------------------------------------------------------------------------------------------------------------|
| **age**                      |  1.4.0  | **PIGSTY** | FEAT  | Apache AGE graph database extension                                                                                        |
| **pointcloud**               |  1.2.5  | **PIGSTY** | FEAT  | A PostgreSQL extension for storing point cloud (LIDAR) data.                                                               |
| **http**                     |   1.6   | **PIGSTY** | FEAT  | HTTP client for PostgreSQL, allows web page retrieval inside the database.                                                 |
| pg_tle                       |  1.2.0  | **PIGSTY** | FEAT  | Trusted Language Extensions for PostgreSQL                                                                                 |
| roaringbitmap                |   0.5   | **PIGSTY** | FEAT  | Support for Roaring Bitmaps                                                                                                |
| **zhparser**                 |   2.2   | **PIGSTY** | FEAT  | Parser for full-text search of Chinese                                                                                     |
| **pgml**                     |  2.7.9  | **PIGSTY** | FEAT  | PostgresML: Use the expressive power of SQL along with the most advanced machine learning algorithms and pretrained models |
| pg_net                       |  0.7.3  | **PIGSTY** | FEAT  | A PostgreSQL extension that enables asynchronous (non-blocking) HTTP/HTTPS requests with SQL                               |
| vault                        |  0.2.9  | **PIGSTY** | FEAT  | Extension for storing encrypted secrets in the Vault                                                                       |
| **pg_graphql**               |  1.4.0  | **PIGSTY** | FEAT  | GraphQL support for PostgreSQL                                                                                             |
| **hydra**                    |  1.0.0  | **PIGSTY** | FEAT  | Hydra is open source, column-oriented Postgres extension                                                                   |

If you have any extension you want to use in Pigsty, please feel free to comment here, and I'll consider building an RPM and adding it to Pigsty's RPM repo.

TODO LIST:

- [x] [imgsmlr](https://github.com/postgrespro/imgsmlr)
- [x] [pg_bigm](https://github.com/pgbigm/pg_bigm)
- [x] [RDKit](https://github.com/rdkit/rdkit)
- [ ] [Parquet S3 FDW](https://github.com/pgspider/parquet_s3_fdw)
- [ ] [PGTDE](https://github.com/Percona-Lab/postgres-tde-ext)
- [ ] OrioleDB
- [ ] ZomboDB
- [ ] Neon Stack
- [ ] [PGroonga](https://github.com/pgroonga/pgroonga) (Skip due to extra deps)
- [x] Supabase Stack
  - [x] pg_net
  - [x] http
  - [x] pgjwt
  - [x] vault
  - [x] pg_graphql
  - [x] pg_tle

**Comment by rinshadka** [comment]
HI,

Installed latest 2.4.1 , but while trying to enable pg_tle extension ( CREATE EXTENSION pg_tle ), got controls file missing error. But in the release note of 2.4.0 I found that pg_tle is included. Am i missing anything. 

Thanks.

**Comment by Vonng** [comment]
> HI,
> 
> Installed latest 2.4.1 , but while trying to enable pg_tle extension ( CREATE EXTENSION pg_tle ), got controls file missing error. But in the release note of 2.4.0 I found that pg_tle is included. Am i missing anything.
> 
> Thanks.

I checked on EL7 - EL9, PG 14 & PG 15, the `pg_tle` can be `CREATE` without error. 

Checklist:
- [ ] The `pg_tle_15` is added to `pg_extensions` or manually installed all cluster members
- [ ] The `pg_tle` is added to `pg_libs` or manually configured into `shared_preload_libraries` on all cluster members

Additional info required
- [ ] detailed os version info
- [ ] `ls -al /www/pigsty/pg_tle_15-*` rpm list
- [ ] `rpm -qlp /www/pigsty/pg_tle_15-*` rpm content

**Comment by rinshadka** [comment]
Thanks @Vonng , Actually I have installed Pigsty to my existing PostgreSQL v13 database. Might that be causing issue. I will try the same in a new PostgreSQL v15 service.

**Comment by jie123108** [comment]
I am using the following extension on a system. I want to migrate to a pigsty system. Can pigsty support them?

## imgsmlr

ImgSmlr – is a PostgreSQL extension which implements similar images searching functionality.

## pg_bigm

The pg_bigm module provides full text search capability in [PostgreSQL](https://www.postgresql.org/). This module allows a user to create 2-gram (bigram) index for faster full text search.


## pgroonga

PGroonga makes PostgreSQL fast full text search platform for all languages!

@Vonng  Thank you for developing such a great system. It feels like a treasure trove with so many features that I would love to use.

**Comment by Vonng** [comment]
> I am using the following extension on a system. I want to migrate to pigsty. Can pigsty support them?
> 
> ## imgsmlr
> ImgSmlr – is a PostgreSQL extension which implements similar images searching functionality.
> 
> ## pg_bigm
> The pg_bigm module provides full text search capability in [PostgreSQL](https://www.postgresql.org/). This module allows a user to create 2-gram (bigram) index for faster full text search.
> 
> ## pgroonga
> PGroonga makes PostgreSQL fast full text search platform for all languages!
> 
> @Vonng Thank you for developing such a great system. It feels like a treasure trove with so many features that I would love to use.

great extensions, maybe we can add them in v2.5.0.
