### ISSUE TITLE
New Module: Cassandra

### ISSUE THREAD

**Issue by yishenggudou** [Vonng/pigsty#319]
[cassandra](https://cassandra.apache.org/_/index.html) Apache Cassandra is an open source NoSQL distributed database trusted by thousands of companies for scalability and high availability without compromising performance. Linear scalability and proven fault-tolerance on commodity hardware or cloud infrastructure make it the perfect platform for mission-critical data.

So can you support `cassandra`  deployment and hosting

**Comment by Vonng** [comment]
Pigsty is a PostgreSQL-centric distribution.  only have limited developers, which are all PostgreSQL experts but none of us are familiar with Cassandra.
We can maintain some peripheral components like etcd / MinIO / Redis / prometheus which are closely related to PostgreSQL. 
We would be very happy if anyone could reuse the infra and contribute a Cassandra module implementation.

**Comment by Vonng** [comment]
We have no more spare manpower for this feature, but if anyone is interested in contribing one, I could help.
