### ISSUE TITLE
How to protect the infra portal from the public

### ISSUE THREAD

**Issue by kaka-ruto** [Vonng/pigsty#326]
How do I password-protect the infra_portal dashboard such that you cannot access any of the services via the web interface without providing the correct password and username?

**Comment by Vonng** [comment]
Here are some common security considerations: https://doc.pigsty.cc/#/SECURITY

Do not expose any port to the Internet; except 80/443, the infra portal

- Grafana/Prometheus are bind to all IP address by default for convenience.
- Modify their bind configuration to listen on localhost/intranet IP and expose by Nginx.
- You can also use security group / firewall rules / iptables to restrict access from intranet only or limited CIDR.
- Protect your nginx with an SSO authentication (use grafana auth header)

**Comment by kaka-ruto** [comment]
Those are a bit of heavy terms for me 😅 . I'm a one person solopreneur, doing everything from frontend to now setting up the databases. I am not that proficient with Devops :)

What would you advise a small team without the knowledge to develop the cool tech? A simple way to just prevent outside access to all my dashboards incase someone got my db IP

**Comment by Vonng** [comment]
> Those are a bit of heavy terms for me 😅 . I'm a one person solopreneur, doing everything from frontend to now setting up the databases. I am not that proficient with Devops :)
> 
> 
> 
> What would you advise a small team without the knowledge to develop the cool tech? A simple way to just prevent outside access to all my dashboards incase someone got my db IP

In that case: if your admin node is inside intranet nothing special has to be done : just change the default grafana/haproxy admin password is sufficient.

And it’s not wise to expose the node directly to the public Internet at all. If you insist so you’d better limit accessing to that node with IPTABLE & SecurityGroups in addition to changing the default password.

And you can also have fine-grained access control in Grafana, you can revoke Viewer privileges from anonymous to prevent them access any info

**Comment by kaka-ruto** [comment]
Thanks very much @Vonng . I will try those and share what I find :)
