### ISSUE TITLE
can not follow the 'Get Started' guide, stuck at '[FAIL] ansible = not found'

### ISSUE THREAD

**Issue by hectorchanht** [Vonng/pigsty#342]
using it on the teminal of sealos
after running 'curl -fsSL https://get.pigsty.cc/latest | bash'
then cd ~/pigsty and ./bootstrap
end up with '[FAIL] ansible = not found'
it happens depite y/n is input for downloading Cache /tmp/pkg.tgz
i am newbie to this, thank you in advanced

root@tek2kpqsr:~/pigsty# ./bootstrap
bootstrap pigsty v2.5.0 begin
[ OK ] region = default
[ OK ] kernel = Linux
[ OK ] machine = x86_64
[ OK ] package = deb,apt
[ OK ] vendor = ubuntu (Ubuntu)
[ OK ] version = 20 (20.04)
[ OK ] sudo = root ok
[ IN ] Cache /tmp/pkg.tgz not exists, download? (y/n):
=> n
[WARN] cache = missing and skip download
[WARN] repo = skip (/tmp/pkg.tgz not exists)
./bootstrap: line 438: sudo: command not found
[ OK ] repo file = add ubuntu focal default upstream
./bootstrap: line 532: sudo: command not found
[ OK ] repo cache = created
./bootstrap: line 569: sudo: command not found
./bootstrap: line 570: sudo: command not found
[FAIL] ansible = not found

**Comment by Vonng** [comment]
Well ... `sudo`` is not in your path...

I wounder if it is a valid BM/VM environment or a trimed container
