### ISSUE TITLE
单机安装报错

### ISSUE THREAD

**Issue by megatronyy** [Vonng/pigsty#344]
系统：ubuntu 20.04 单机安装
错误：
`
 failed: [192.168.1.111] (item=postgresql-*-${pg_version}) => {"ansible_loop_var": "item", "cache_update_time": 1701249579, "cache_updated": false, "changed": false, "item": "postgresql-*-${pg_version}", "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"      install 'postgresql-client-15' 'postgresql-pgml-15' 'postgresql-plperl-15' 'postgresql-plpython3-15' 'postgresql-pltcl-15' 'postgresql-server-dev-15'' failed: E: Unable to correct problems, you have held broken packages.\n", "rc": 100, "stderr": "E: Unable to correct problems, you have held broken packages.\n", "stderr_lines": ["E: Unable to correct problems, you have held broken packages."], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nSome packages could not be installed. This may mean that you have\nrequested an impossible situation or if you are using the unstable\ndistribution that some required packages have not yet been created\nor been moved out of Incoming.\nThe following information may help to resolve the situation:\n\nThe following packages have unmet dependencies:\n postgresql-pgml-15 : Depends: python3-dev but it is not going to be installed\n                      Depends: libpython3-dev but it is not going to be installed\n postgresql-server-dev-15 : Depends: libpq-dev (>= 15~~) but it is not going to be installed\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "Some packages could not be installed. This may mean that you have", "requested an impossible situation or if you are using the unstable", "distribution that some required packages have not yet been created", "or been moved out of Incoming.", "The following information may help to resolve the situation:", "", "The following packages have unmet dependencies:", " postgresql-pgml-15 : Depends: python3-dev but it is not going to be installed", "                      Depends: libpython3-dev but it is not going to be installed", " postgresql-server-dev-15 : Depends: libpq-dev (>= 15~~) but it is not going to be installed"]}
`

请大神帮看看，用什么版本比较合适

**Comment by Vonng** [comment]
Ubuntu 22.04 / 20.04 刚刚新引入，生产使用建议使用 EL 系操作系统，Rocky 8.8 / 9.2。出现 RPM 冲突时请参考 FAQ https://doc.pigsty.cc/#/FAQ?id=installation 解决。

```
rm -rf /www/pigsty/repo_complete    # delete the repo_complete flag file to mark this repo incomplete
rm -rf SomeBrokenPackages           # delete problematic RPM/DEB packages
./infra.yml -t repo_upstream        # write upstream repos. you can also use /etc/yum.repos.d/backup/*
./infra.yml -t repo_pkg             # download rpms according to your current OS
```
