### ISSUE TITLE
PGCAT Table的dashboard 无法获取监控数据

### ISSUE THREAD

**Issue by SiRain** [Vonng/pigsty#357]
![image](https://github.com/Vonng/pigsty/assets/10768708/2b268814-7dac-49a9-8f0a-bb860367428e)
我 copy 一份沙箱的 inventory 问件，修改了 cmdb.sql 中的10.10.10.10的占位符为自己的管理节点ip (102, 'admin_ip', '"192.168.2.80"', 'INFRA', 'META', 'ip', 'G', 'admin node ip address', NULL)  完成部署后， PGCAT Table的dashboard中出现错误： A
Status: 500. Message: db query error: pq: invalid input syntax for type oid: ""

**Comment by Vonng** [comment]
你这个问题和 CMDB 还有里面的元数据没有关系吧。就是 datasouce 找不到数据库 OID。

**Comment by SiRain** [comment]
我看了grafana里面的查询语句，不知道为什么oid查询不到，我也是按照官网的方法是安装的demo.yml，刚开始用pigsty，里面的逻辑不是非常熟悉，搞不清楚为什么会出现这样的问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Feng Ruohang ***@***.***&gt;
发送时间: 2024年1月5日 21:41
收件人: Vonng/pigsty ***@***.***&gt;
抄送: SiRain ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Vonng/pigsty] PGCAT Table的dashboard 无法获取监控数据 (Issue #357)





 
你这个问题和 CMDB 还有里面的元数据没有关系吧。就是 datasouce 找不到数据库 OID。

**Comment by SiRain** [comment]
你好：
    对比了我自己的环境和demo沙箱环境 relname 变量获取不到值，是不是因为pg_extensions 中 pgml-15* 模块未安装导致的，我的机器是centos7
https://github.com/Vonng/pigsty/blob/master/app/pgml/README.md 文章中看 pgml_15 支持ubuntu和el8、9


datname 变量获取到的值也不一样



***@***.***
 
发件人： Feng Ruohang
发送时间： 2024-01-05 21:41
收件人： Vonng/pigsty
抄送： SiRain; Author
主题： Re: [Vonng/pigsty] PGCAT Table的dashboard 无法获取监控数据 (Issue #357)
你这个问题和 CMDB 还有里面的元数据没有关系吧。就是 datasouce 找不到数据库 OID。
