### ISSUE TITLE
Patroni支持配置Zookeeper集群

### ISSUE THREAD

**Issue by Asakiny** [Vonng/pigsty#360]
对于大数据场景，比较常用Zookeeper作为高可用状态维护的组件，我们是否可以考虑为Pigsty提供可选的DCS模块，比如加入Zookeeper的配置

**Comment by Vonng** [comment]
我们仔细评估过 Consul，ETCD，ZK，对 ZK 的印象很差。
并且最终决定收敛到 etcd ，连已有的 consul 支持都不再继续了，更别提ZK了。
less is more，我们确实没有这样的计划，请见谅。
