### ISSUE TITLE
node-instance 面板 nvme没有单位转换

### ISSUE THREAD

**Issue by zzzhouuu** [Vonng/pigsty#367]
<img width="634" alt="CleanShot 2024-02-19 at 12 11 01@2x" src="https://github.com/Vonng/pigsty/assets/8481484/cc37e32c-1653-4a88-8d7f-842c9b6c8be8">

**Comment by Vonng** [comment]
fixed, will be released in v2.6

**Comment by Vonng** [comment]
https://github.com/Vonng/pigsty/commit/a8b5c69293760ae14bff7b04560385c75f4d7748
