### ISSUE TITLE
About node scale and NUMA optimizations

### ISSUE THREAD

**Issue by licson** [Vonng/pigsty#371]
Hello,

My company is currently running a 3-node Postgres system, each with about a terabyte of RAM hosting all company databases.

We recently are looking to segregate different internal databases to improve efficiency and manageability and I found this project that makes it easy to do so. However when I checked the starter guide it states that the maximum memory scalability per node only goes up to 512GB which is only half of what our nodes have.

I wonder if there's something preventing the use of more memory or it's only the largest config you've tested and it will work with higher memory machines too. Also, due to the higher amount of memory we are using 4-way CPU per node and I also have questions about the NUMA optimizations of the built-in Postgres configuration. Is it fully managed by the software or is there a way to manually tune the database instance?

I am glad to hear your reply soon.

**Comment by Vonng** [comment]
- Pigsty does not impose any restrictions on node CPU / memory, and neither does PostgreSQL. Actually PostgreSQL has a very good reputation on vertical scalability

- The mainstream servers we use all come with 512GB of memory, but we also have systems with several TBs of memory on a single machine.

- We don't have NUMA optimization. but we have options to disable NUMA. you can ignore it and optimize by manually binding database process to specific cores.
