### ISSUE TITLE
linux 主机名称被更改

### ISSUE THREAD

**Issue by gospider007** [Vonng/pigsty#377]
安装这个软件后，linux 主机名称被改成  pg-meta-1  了，为啥

**Comment by Vonng** [comment]
有参数控制这一点。 node_id_from_pg 请参阅文档

**Comment by Vonng** [comment]
https://pigsty.io/docs/reference/param/#node_id_from_pg
https://pigsty.io/docs/reference/param/#nodename_overwrite
