### ISSUE TITLE
"pg: command not found" on ubuntu 2204 

### ISSUE THREAD

**Issue by sunxk** [Vonng/pigsty#379]
Environment: ubuntu 2204 VM，root user

```
root@meta:~/pigsty# pg edit-config
pg: command not found
root@meta:~/pigsty# 
```

It's worked well on rocky8 VM

**Comment by Vonng** [comment]
Sorry i didn't reproduce that in a 22.04 deployment...
Could you provide more details about your deployment?
And `pg` is an alias for `patronictl`, you can always use that.

**Comment by SeanHoganSkyHawk** [comment]
FYI: I hit that problem too, but it was resolved when I logged out and back in. I presume it's because pg is an alias or function that only comes into existence when the shell starts.

**Comment by sunxk** [comment]
> FYI: I hit that problem too, but it was resolved when I logged out and back in. I presume it's because pg is an alias or function that only comes into existence when the shell starts.

@Vonng @SeanHoganSkyHawk 
add the following lines to the end of the file /root/.bashrc:
```
if [ -f /etc/profile.d/pg-alias.sh ]; then
    . /etc/profile.d/pg-alias.sh
fi
```
