### ISSUE TITLE
在centos 7.9 中部署时，安装 pg_extensions --> postgis34_${pg_version}* 会报错

### ISSUE THREAD

**Issue by iamdzk** [Vonng/pigsty#380]
在centos 7.9 中部署时，安装 pg_extensions --> postgis34_${pg_version}* 会报错。因为仓库中只有 postgis33_${pg_version}* ，没有 postgis34_${pg_version}*。将其改为 postgis33_${pg_version}* 后报错消失，安装成功

![image](https://github.com/Vonng/pigsty/assets/58968475/c651af7f-56bf-4785-be73-885a3e9a1a18)

**Comment by Vonng** [comment]
Yes that's a known issue: https://github.com/Vonng/pigsty/issues/375. fixed an will be released in the next minor release
