### ISSUE TITLE
Fail to install PVE LXC container environment

### ISSUE THREAD

**Issue by crazyweeds** [Vonng/pigsty#381]
TASK [node : enable kernel module] ***********************************************************************************************************************************************************************************************************************
ok: [192.168.200.21] => (item=softdog)
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: FileNotFoundError: [Errno 2] No such file or directory: '/lib/modules/6.2.9-1-pve/modules.builtin'
failed: [192.168.200.21] (item=br_netfilter) => {"ansible_loop_var": "item", "changed": false, "item": "br_netfilter", "msg": "[Errno 2] No such file or directory: '/lib/modules/6.2.9-1-pve/modules.builtin'", "name": "br_netfilter", "params": "", "state": "present"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: FileNotFoundError: [Errno 2] No such file or directory: '/lib/modules/6.2.9-1-pve/modules.builtin'
failed: [192.168.200.21] (item=ip_vs) => {"ansible_loop_var": "item", "changed": false, "item": "ip_vs", "msg": "[Errno 2] No such file or directory: '/lib/modules/6.2.9-1-pve/modules.builtin'", "name": "ip_vs", "params": "", "state": "present"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: FileNotFoundError: [Errno 2] No such file or directory: '/lib/modules/6.2.9-1-pve/modules.builtin'
failed: [192.168.200.21] (item=ip_vs_rr) => {"ansible_loop_var": "item", "changed": false, "item": "ip_vs_rr", "msg": "[Errno 2] No such file or directory: '/lib/modules/6.2.9-1-pve/modules.builtin'", "name": "ip_vs_rr", "params": "", "state": "present"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: FileNotFoundError: [Errno 2] No such file or directory: '/lib/modules/6.2.9-1-pve/modules.builtin'
failed: [192.168.200.21] (item=ip_vs_wrr) => {"ansible_loop_var": "item", "changed": false, "item": "ip_vs_wrr", "msg": "[Errno 2] No such file or directory: '/lib/modules/6.2.9-1-pve/modules.builtin'", "name": "ip_vs_wrr", "params": "", "state": "present"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: FileNotFoundError: [Errno 2] No such file or directory: '/lib/modules/6.2.9-1-pve/modules.builtin'
failed: [192.168.200.21] (item=ip_vs_sh) => {"ansible_loop_var": "item", "changed": false, "item": "ip_vs_sh", "msg": "[Errno 2] No such file or directory: '/lib/modules/6.2.9-1-pve/modules.builtin'", "name": "ip_vs_sh", "params": "", "state": "present"}

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************************
192.168.200.21             : ok=27   changed=12   unreachable=0    failed=1    skipped=24   rescued=0    ignored=0   
localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=4    rescued=0    ignored=0   

root@Pigsty:~/pigsty#

**Comment by Vonng** [comment]
Running in Container is not officially supported yet.
While I'm working on it.

There are certian limitations when running in docker containers:

```
node_dns_method: none
node_ntp_enabled: false
dns_enabled: falses
```

Will adding a new parameters to bypass the `/etc/hosts` managed by docker issue, too.

```
node_add_hosts: false
```

**Comment by Vonng** [comment]
now we have a [`docker.yml`] for running inside docker VM: https://github.com/Vonng/pigsty/blob/master/files/pigsty/docker.yml
