### ISSUE TITLE
TASK [repo : remake repo cache]

### ISSUE THREAD

**Issue by fanwang1977** [Vonng/pigsty#382]
就是默认的安装，在安装 pigsty 过程中，执行到./install.yml，在屏幕显示TASK [repo : remake repo cache] *****以后，就一直停在这个位置，没有任何动静了。不知道是什么原因。
操作系统是 Ubuntu 22.04.04 LTS

**Comment by Vonng** [comment]
这一步实际上在执行 `apt update` ，你要确认你的服务器确实能访问上游 apt 源，否则应当考虑本地离线安装。
