### ISSUE TITLE
install failed on Rocky Linux 9 : FAILED! => {"msg": "You need to install \"jmespath\" prior to running json_query filter"}

### ISSUE THREAD

**Issue by nining** [Vonng/pigsty#389]
I have executed the following command:
`
sudo dnf install -y ansible python3.11-jmespath
`
And when executing install.yaml, the following error message was throwed:
`
TASK [pg_id : get pgsql identity] 
fatal: [192.168.1.6]: FAILED! => {"msg": "You need to install \"jmespath\" prior to running json_query filter"}
`

**Comment by nining** [comment]
I installed the python3-jmespath package, and it resolved the issue.

**Comment by Vonng** [comment]
Sometimes you have to install both python3-jmespath & python3.11-jmespath to resolve this issue on el8/el9
