### ISSUE TITLE
 rocky linux 9 install pigsty faild start progres

### ISSUE THREAD

**Issue by AdamYLK** [Vonng/pigsty#390]
### What happend? (REQUIRED)

a new empty instance vm： rocky linux 9，install pigsty，when bash finshed ./install.yml
there is one error
![image](https://github.com/Vonng/pigsty/assets/13025698/598b32d4-71e5-4d2e-ad22-a781f5dda2b6)
and when i checked，i find postgres service didn't start
then i check it's log，and try start again it's faild again
![image](https://github.com/Vonng/pigsty/assets/13025698/584edb79-5be1-4bce-a53f-ae07b6126dfb)
then i check progres logs，em.. seems like something miss when install progres 
```
2024-04-11 13:55:46.636 P00   INFO: archive-push command begin 2.51: [pg_wal/000000010000000000000001] --archive-async --compress-type=lz4 --exec-id=48203-ff3e793c --log-level-console=info --log-level-file=detail --log-path=/pg/log/pgbackrest --pg1-path=/pg/data --process-max=4 --repo1-path=/pg/backup --spool-path=/pg/tmp --stanza=pg-meta
ERROR: [103]: unable to find a valid repository:
       repo1: [FileMissingError] unable to load info file '/pg/backup/archive/pg-meta/archive.info' or '/pg/backup/archive/pg-meta/archive.info.copy':
       FileMissingError: unable to open missing file '/pg/backup/archive/pg-meta/archive.info' for read
       FileMissingError: unable to open missing file '/pg/backup/archive/pg-meta/archive.info.copy' for read
       HINT: archive.info cannot be opened but is required to push/get WAL segments.
       HINT: is archive_command configured correctly in postgresql.conf?
       HINT: has a stanza-create been performed?
       HINT: use --no-archive-check to disable archive checks during backup if you have an alternate archiving scheme.
2024-04-11 13:55:47.742 P00   INFO: archive-push command end: aborted with exception [103]
```
i try to revert vm status to begin，it's third time i install faild，i need help..

### Pigsty Version & OS Version (REQUIRED)
version: v2.6.0                   # pigsty version string
pg_version: 16                    # el8 / el9 will use postgresql 16 as the default major version

```
[root@edu-k8s-001 pigsty]# cat /etc/os-release
NAME="Rocky Linux"
VERSION="9.3 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.3"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.3 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.3"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.3"
```

### Pigsty Config File (REQUIRED)
[pigsty.zip](https://github.com/Vonng/pigsty/files/14942053/pigsty.zip)
 

### Error Log
[postgresql-2024-04-11.log](https://github.com/Vonng/pigsty/files/14942074/postgresql-2024-04-11.log)

**Comment by Vonng** [comment]
It seems that postgresql is not properly installed? (from no such file error info)

Check /www/pigsty repo first to see whether the repo_packages are downloaded and installed properly.

**Comment by AdamYLK** [comment]
i check this path
/www/pigsty.repo file is
```
[pigsty]
name=Pigsty Local Yum Repo pigsty
baseurl=http://192.168.110.61:80/pigsty
skip_if_unavailable = 1
enabled = 1
priority = 1
gpgcheck = 0
module_hotfixes=1
```

the files in /www/pigsty，seems like is ready and right
![image](https://github.com/Vonng/pigsty/assets/13025698/07cdbe82-d0be-46e9-98b1-f3b2d8dc5e0a)

**Comment by AdamYLK** [comment]
the things that confuse me is the service can be use，and service's log show miss files 
need i use rocky linux 8.9?
if this problem is a common problem，may be it need check

**Comment by AdamYLK** [comment]
em... i need add more info
in g.pigsty，other infomation is ready, only miss pgsql（and i know it's because pgsql service is down，i juse want show other module is ready and right）
![image](https://github.com/Vonng/pigsty/assets/13025698/3cb37394-dc80-4de0-9101-43652fe6a4a3)

**Comment by Vonng** [comment]
I am agog, I am aghast, Are you using windows WSL?……
Seems your infra & etcd works well but not PGSQL.
try `./pgsql.yml` to install PostgreSQL separately

**Comment by AdamYLK** [comment]
of couse not... wsl is bad things
it's a vm from vmware esxi, i promise that
![image](https://github.com/Vonng/pigsty/assets/13025698/38cdd22b-637f-4725-bda6-b54a940ef2c8)

i try you suggest
it's works，finished install and register to grafana
![image](https://github.com/Vonng/pigsty/assets/13025698/a979a9cd-a343-470a-8e10-60db908b2d73)

What I can't confirm is whether this successful installation is related to me actively granting the /pg and /data paths to the database user...
