### ISSUE TITLE
PostgreSQL extension installation failed

### ISSUE THREAD

**Issue by ZanePoe** [Vonng/pigsty#394]
I am conducting some technical selection.I just installed pigsty on ubuntu22.04 and want to install as many postgresql extensions as possible.
I tested them one by one and only successfully installed these extensions.
![2a1e74f1398f870caa8766098a8b0cf](https://github.com/Vonng/pigsty/assets/16047426/c72ead3b-8f34-4a4f-a92c-a5a29e5199f8)
The usual errors are like this "(item=postgresql-16-set-user postgresql-16-show-plans) => {"ansible_loop_var": "item", "changed": false, "item": "postgresql-16-set-user postgresql-16-show-plans", "msg": "No package matching 'postgresql-16-set-user' is available"}"
![32625f9609a4ea1764b74fe2be15363](https://github.com/Vonng/pigsty/assets/16047426/9e7c2400-68c5-48ba-8009-67dec7b324ba)

My yml file is as follows:
[pigsty.txt](https://github.com/Vonng/pigsty/files/15064414/pigsty.txt)

**Comment by Vonng** [comment]
extensions needs to be downloaded before installation by default.
Check your `repo_packages` and `/www/pigsty/` content.

**Comment by Vonng** [comment]
> I follow this steps： ![image](https://private-user-images.githubusercontent.com/16047426/343726953-36490529-f665-4d72-806a-9b52f480d271.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2MjQzOTQsIm5iZiI6MTcxOTYyNDA5NCwicGF0aCI6Ii8xNjA0NzQyNi8zNDM3MjY5NTMtMzY0OTA1MjktZjY2NS00ZDcyLTgwNmEtOWI1MmY0ODBkMjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDAxMjEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmOGIzZjgzZjYxOWZhNTA3YmJkZjI3ZTQ1NzE2ZTlkNDk1ZDNkMDU4YmYzYmU4YjBhMWZiZjUwMTU5NzNlZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J2HV4FlPlV9VgL3qW9dk8oRgldl5_PLb3iu9z4GX7m8) but `cd /www/pigsty; repotrack "some_new_package_name" `
> 
> This code reports an error：
> 
> ```
> repotrack：未找到命令
> ```
> 
> Why not download extensions automatically？

well, the `repotrack` is for EL distributions, you should use `apt download` for ubuntu / debian distros.
