### ISSUE TITLE
failed to load timescaledb extension in rocky9

### ISSUE THREAD

**Issue by dkzhong** [Vonng/pigsty#400]
在roky9 Linux中安装好pigsty v2.6.0，在psql环境执行”CREATE EXTENSON timescaledb; “ 出错。

出错信息是”ERROR:  SQL error: TokenizerError("Unterminated dollar-quoted string at or near \"BODY\" at Line: 872, Column 21")“。在Debian系的Ubuntu22.04和Debian 12中也是提示这个错误。

使用系统原生的postgresql 16，从源代码安装timescaledb，运行正常。

请问这是什么原因？谢谢

**Comment by Vonng** [comment]
这有点奇怪，我复现一下试试。有更详细一些的上下文吗？是否可能是 psqlrc 的问题。

**Comment by dkzhong** [comment]
执行create extension timescaledb；输出就一行错误提示，
![微信图片_20240430093049](https://github.com/Vonng/pigsty/assets/7707784/0a6bbc4f-71d2-4fe2-ac15-26f0bbe5756e)
不知道日志文件在哪里。
试过好几台机器了，包括物理机、虚拟机，都出现这个错误

**Comment by Vonng** [comment]
无法在 EL9 部署中复现，是离线安装包里的，还是直接从上游在线安装的？
可以试试 RockyLinux 8.9

**Comment by dkzhong** [comment]
就是用离线安装包安装的

**Comment by dkzhong** [comment]
就是按照https://pigsty.io/zh/docs/setup/install/的说明安装的，没有事先下载离线安装包

**Comment by dkzhong** [comment]
rocky8.9的话就出现parasdedb在没法加载pgvector插件的问题
![2024-05-16 16-50-26屏幕截图](https://github.com/Vonng/pigsty/assets/7707784/87522aea-fad8-45ee-b1d7-21541f271092)

**Comment by dkzhong** [comment]
rocky8.9的话就出现parasdedb没法加载pgvector插件的问题
![2024-05-16 16-50-26屏幕截图](https://github.com/Vonng/pigsty/assets/7707784/e5da782d-b0ed-4683-b231-8d132f156222)

**Comment by dkzhong** [comment]
不用管了，升级到2.7就好了
