### ISSUE TITLE
Install postgres packages error on Ubuntu 22.04.4 LTS

### ISSUE THREAD

**Issue by blaszta** [Vonng/pigsty#404]
The install.yml end with this:

`TASK [pgsql : install postgres packages] ******************************************************************************
ok: [192.168.15.220] => (item=postgresql-*-${pg_version})
ok: [192.168.15.220] => (item=patroni pgbouncer pgbackrest pg-exporter pgbadger vip-manager)
failed: [192.168.15.220] (item=postgresql-${pg_version}-repack postgresql-${pg_version}-wal2json) => {"ansible_loop_var": "item", "changed": false, "item": "postgresql-${pg_version}-repack postgresql-${pg_version}-wal2json", "msg": "No package matching 'postgresql-16-repack' is available"}

PLAY RECAP ************************************************************************************************************
192.168.15.220             : ok=198  changed=68   unreachable=0    failed=1    skipped=56   rescued=0    ignored=0
localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=4    rescued=0    ignored=0`

Any idea how to fix this?

**Comment by Vonng** [comment]
There's no enough context info for this issue.

You have to check the install ansible log to see if that pacakge is properly downloaded.

check `/www/pigsty` dir for the deb package.
