### ISSUE TITLE
[UI] Grafana page backward error

### ISSUE THREAD

**Issue by waitingsong** [Vonng/pigsty#412]
Error process reproduction：
1. Open link `http://g.pigsty/d/pgsql-instance/pgsql-instance?from=now-1h&to=now&orgId=1`
3. Click zone `PG LOAD` or `CPU` （other seems no problme). link should be  `http://g.pigsty/d/pgsql-instance?var-ins=pg-a-1&viewPanel=38&from=now-1h&to=now`
4. Browser back to the previous page. Note:  press `ESC` no problem
5. Page item crash

Condition:
1. pg instance is the fisrt item ( primary ?)
2. Only link to `PG LOAD` or `CPU`

OS: win10 22H2

Brower:
- FireFox v125.0.3 64bit
- Chrome v124.0.6367.202 64bit

Image 1:

![22a](https://github.com/Vonng/pigsty/assets/1763067/fcbb4697-4537-4cb5-943c-90f9aa801d04)

Image 2:

![23](https://github.com/Vonng/pigsty/assets/1763067/ccd1237d-5cfa-419b-a6f7-27562d6c0ff0)

**Comment by Vonng** [comment]
resolved by https://github.com/Vonng/pigsty/commit/79660533b5e88de2ab7a97592d5519cd4b4008aa
