### ISSUE TITLE
[UI] Grafana page "pgrds-cluster" layout abnormal

### ISSUE THREAD

**Issue by waitingsong** [Vonng/pigsty#414]
page: `http://g.pigsty/d/pgrds-cluster/pgrds-cluster?orgId=1`
cluster: `pg-a` abnormal, image1
cluster: `pg-meta` good, image2

**image1:**
![13a](https://github.com/Vonng/pigsty/assets/1763067/081145cf-c4ad-46b0-8c66-98704981c5e3)

**image2:**
![14](https://github.com/Vonng/pigsty/assets/1763067/6f5bc29e-4465-4ca7-b64c-aa296fa0e564)

**Comment by Vonng** [comment]
Resolved by https://github.com/Vonng/pigsty/commit/2b363bf5a8b79a1532135e87e8e68f8fc4026680
