### ISSUE TITLE
Ubuntu 22.04.4 Server-node modules not installing

### ISSUE THREAD

**Issue by sher1** [Vonng/pigsty#425]
I have run the curl command, followed by 
cd ~/pigsty
./bootstrap
./configure
./install.yml and I get this error
libc6-dev : Depends: libc6 (= 2.35-0ubuntu3.7) but 2.35-0ubuntu3.8 is to be installed"
I am attaching a log of the output from the install.yml command

System info:
Description ID: Ubuntu
Description:       Ubuntu 22.04.4 LTS
Release:              22.04
Codename:         jammy

Kernel 5.15.0-112-generic
[install.log](https://github.com/user-attachments/files/15779304/install.log)

**Comment by Vonng** [comment]
It seems the latest Ubuntu minor update has an apt conflict with the pre-built offline package.
Maybe you can try to perform an online install from the Internet 
(i.e. do not answer `y` during bootstrap)

**Comment by ddorian** [comment]
I had the same error and it worked with online install.
