### ISSUE TITLE
Pigsty v2.8 feature planning

### ISSUE THREAD

**Issue by Vonng** [Vonng/pigsty#427]
- [x] Grafana 11 migration
- [x] PG Exporter 0.7 for PG 17
- [x] PG 17 beta template
- [ ] Observability enhancement
- [x] bump duckdb, libduckdb, duckdb_fdw to v1.0.0
- [x] bump paradedb extensions to v0.8
- [x] ProxyEnv for Docker
- [x] Nginx infra_portal config for existing certs
- [ ] Migration pigsty repo entirely to Cloudflare? 
- [x] Bump FerretDB, SealOS
- [x] Add timescale pgvectorscale extension

Not Planned

- [ ] bump default rocky minor version to 8.10 and 9.4
- [ ] VictoriaMetrics & Vector ?

**Comment by CHEN-Jing194** [comment]
Can parquet_s3_fdw v1.1.0 appear in this version? 🙏

**Comment by Vonng** [comment]
> Can parquet_s3_fdw v1.1.0 appear in this version? 🙏

It's already included in the previous v2.7.0 release.
