### ISSUE TITLE
Pigsty2.7 error deploying rocky9.3.

### ISSUE THREAD

**Issue by caesar168** [Vonng/pigsty#436]
![bcc210cdd25ac4ac8ee2e676822a8d5](https://github.com/Vonng/pigsty/assets/4076070/e1ed9383-5ce5-476f-823d-312e292dabdc)

TASK [node : install default node packages] **********************************************
failed: [192.168.10.100] (item=lz4,unzip,bzip2,zlib,yum,pv,jq,git,ncdu,make,patch,bash,lsof,wget,uuid,tuned,nvme-cli,numactl,grubby,sysstat,iotop,htop,rsync,tcpdump,chrony,python3) => {"ansible_loop_var": "item", "changed": false, "failures": ["No package pv available.", "No package git available.", "No package ncdu available.", "No package patch available.", "No package numactl available.", "No package sysstat available.", "No package iotop available.", "No package htop available."], "item": "lz4,unzip,bzip2,zlib,yum,pv,jq,git,ncdu,make,patch,bash,lsof,wget,uuid,tuned,nvme-cli,numactl,grubby,sysstat,iotop,htop,rsync,tcpdump,chrony,python3", "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}
failed: [192.168.10.100] (item=netcat,socat,ftp,lrzsz,net-tools,ipvsadm,bind-utils,telnet,audit,ca-certificates,openssl,readline,vim-minimal,node_exporter,etcd,haproxy,python3-pip) => {"ansible_loop_var": "item", "changed": false, "failures": ["No package netcat available.", "No package socat available.", "No package ftp available.", "No package lrzsz available.", "No package telnet available.", "No package node_exporter available.", "No package etcd available.", "No package haproxy available.", "No package python3-pip available."], "item": "netcat,socat,ftp,lrzsz,net-tools,ipvsadm,bind-utils,telnet,audit,ca-certificates,openssl,readline,vim-minimal,node_exporter,etcd,haproxy,python3-pip", "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}

**Comment by Vonng** [comment]
It seems something wrong with your software repo, maybe network. try the offline installation instead.

**Comment by caesar168** [comment]
Fresh install of rockylinux9.3, clean, is also pigsty's default repo。
