### ISSUE TITLE
TASK [repo : download repo url packages]  failed: [192.168.1.201] (item=https://repo.pigsty.cc/etc/plugins.tgz) 

### ISSUE THREAD

**Issue by AndrewYukon** [Vonng/pigsty#441]
When installed on RockyLinux, occurred this error:
TASK [repo : download repo url packages] ***************************************
ok: [192.168.1.201] => (item=https://repo.pigsty.cc/etc/pev.html)
ok: [192.168.1.201] => (item=https://repo.pigsty.cc/etc/chart.tgz)
failed: [192.168.1.201] (item=https://repo.pigsty.cc/etc/plugins.tgz) => {"ansible_loop_var": "item", "changed": false, "dest": "/www/pigsty/", "elapsed": 1, "gid": 0, "group": "root", "item": "https://repo.p
igsty.cc/etc/plugins.tgz", "mode": "0755", "msg": "Request failed", "owner": "root", "response": "HTTP Error 404: Not Found", "secontext": "unconfined_u:object_r:default_t:s0", "size": 61440, "state": "direct
ory", "status_code": 404, "uid": 0, "url": "https://repo.pigsty.cc/etc/plugins.tgz"}
...ignoring

And I found this URL 'https://repo.pigsty.cc/etc/plugins.tgz' unreachable.

****************************************
$  grep version  pigsty.yml 
          #[ Featured & AM     ]# - apache-age_$v* pg_graphql_$v pg_jsonschema_$v jsquery_$v* pg_hint_plan_$v* hypopg_$v* pg_ivm_$v* pgmq_$v pgq_$v* pgtt_$v* temporal_tables_$v* e-maj_$v* periods_$v* table_version_$v* pg_statement_rollback_$v* hll_$v* rum_$v
    version: v2.7.0                   # pigsty version string

$ cat /etc/os-release
NAME="Rocky Linux"
VERSION="8.10 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.10"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.10 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.10"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.10"

**Comment by Vonng** [comment]
fixed, besides, https://repo.pigsty.io/etc/plugins.tgz is also available
