### ISSUE TITLE
Certificate for https://get.pigsty.cc is expired.

### ISSUE THREAD

**Issue by trevorcapps** [Vonng/pigsty#444]
Subject:  get.pigsty.cc
Altnames: DNS:get.pigsty.cc
Issuer:   TrustAsia RSA DV TLS CA G2

Not valid before: Aug 17 00:00:00 2023 GMT
Not valid after:  Aug 16 23:59:59 2024 GMT

This causes new installs to fail if using the setup script.

**Comment by Vonng** [comment]
The plan was to replace the old repo with the new one.

curl -fsSL https://repo.pigsty.io/get | bash

I'll update the doc asap

**Comment by Vonng** [comment]
Resolved
