### ISSUE TITLE
Replica allow write operation

### ISSUE THREAD

**Issue by akoua** [Vonng/pigsty#455]
Hello I have some issue when I used the dual configuration files. 
I have two nodes on my cluster according the **conf/dual.yml**, I precise the IP 10.10.0.2 when I launch the **configure** script.
At the beginning of startup database cluster all are fine, but If I shutdown the infra node (10.10.0.3), I can only execute a read sql request on the primary node (10.10.0.2), so it's not good for the business. Moreover, when the infra node (10.10.0.3) come back, it's become a primary node, I can write on it and I can write to the node(10.10.0.2) too, unless I set the default postgres port(**5432**). Also the pgBouncer dashboard show that the node(10.10.0.2) is DEAD but it's not the case. 

**I use v3.0.1 version.**

<img width="793" alt="image" src="https://github.com/user-attachments/assets/25db22d6-b877-4596-956b-6ce279303a9c">

**Config description**

`---
#==============================================================#
# File      :   pigsty.yml
# Desc      :   Pigsty Prodbox: two nodes
# Ctime     :   2020-05-22
# Mtime     :   2024-09-15
# Author    :   Test
# License   :   AGPLv3
#==============================================================#

# Config Templates: https://github.com/Vonng/pigsty/tree/master/conf

all:
  children:

    # infra cluster for proxy, monitor, alert, etc..
    infra: { hosts: { 10.10.0.3: { infra_seq: 1 } }}

    # etcd cluster for ha postgres
    etcd:
      hosts:
        10.10.0.3: { etcd_seq: 1, nodename: etcd-1 }
        10.10.0.2: { etcd_seq: 2, nodename: etcd-2 }
      vars: 
        etcd_cluster: etcd
        node_cluster: etcd
        etcd_safeguard: false
        etcd_clean: true

    # postgres example cluster: pg-meta
    pg-meta:
      hosts: 
       10.10.0.3: { pg_seq: 1, pg_role: replica }
       10.10.0.2: { pg_seq: 2, pg_role: primary }
      vars:
        pg_cluster: pg-meta
        pg_users:           
          - {name: dbuser_meta     ,password: DBUser.Meta     ,pgbouncer: true ,roles: [dbrole_admin]     ,comment: pigsty admin user }
          - {name: dbuser_view     ,password: DBUser.Viewer   ,pgbouncer: true ,roles: [dbrole_readonly]  ,comment: read-only viewer for meta database }
          - {name: dbuser_grafana  ,password: DBUser.Grafana  ,pgbouncer: true ,roles: [dbrole_admin]     ,comment: admin user for grafana database    }          
          - {name: security_user   ,password: mustBeChanged2   ,pgbouncer: true ,roles: [dbrole_readwrite] ,comment: kiffer admin user }
        pg_databases:
          - {name: meta ,baseline: cmdb.sql ,comment: pigsty meta database ,schemas: [pigsty] ,extensions: [{name: postgis, schema: public}, {name: timescaledb}]}
          - {name: grafana  ,owner: dbuser_grafana  ,revokeconn: true ,comment: grafana primary database }
          - {name: iam_users, baseline: iam_users.sql, comment: iam database, schemas: [kiffer] }          
        pg_hba_rules:
          - {user: dbuser_view, db: all ,addr: infra ,auth: pwd ,title: 'allow grafana dashboard access cmdb from infra nodes'}       
          - {user: all, db: all, addr: world, auth: ssl, title: 'admin @ everywhere with ssl & pwd'}

        pg_libs: 'timescaledb, $libdir/passwordcheck, pg_stat_statements, auto_explain'
        pg_extensions: [ timescaledb ]        
        pg_vip_enabled: true
        pg_vip_address: 10.10.0.0/16
        pg_vip_interface: eth1
        node_crontab:  # make full backup each 5 minutes everyday
          - '*/5 * * * * postgres /pg/bin/pg-backup full'    
    
        pg_default_service_dest: pgbouncer # default service destination if svc.dest='default'
        pg_default_services:              # postgres default service definitions
          - { name: primary ,port: 5433 ,dest: default  ,check: /primary   ,selector: "[]" }
          - { name: replica ,port: 5434 ,dest: default  ,check: /read-only ,selector: "[]" , backup: "[? pg_role == `primary` || pg_role == `offline` ]" }
          - { name: default ,port: 5436 ,dest: postgres ,check: /primary   ,selector: "[]" }

    vars:                               # global variables
      version: v3.0.1                   # pigsty version string
      admin_ip: 10.10.0.3               # admin node ip address
      region: europe                    # upstream mirror region: default|china|europe
      node_tune: oltp                   # oltp|olap|tiny|cirt
      pg_conf: oltp.yml                 # oltp.yml|olap.yml|tiny.yml|cirt.yml
      infra_portal:                     # domain names and upstream servers
        home         : { domain: h.pigsty }
        grafana      : { domain: g.pigsty ,endpoint: "${admin_ip}:3000" , websocket: true }
        prometheus   : { domain: p.pigsty ,endpoint: "${admin_ip}:9090" }
        alertmanager : { domain: a.pigsty ,endpoint: "${admin_ip}:9093" }
        blackbox     : { endpoint: "${admin_ip}:9115" }
        loki         : { endpoint: "${admin_ip}:3100" }      
        postgrest    : { domain: api.pigsty  ,endpoint: "127.0.0.1:8884" }      
        pgweb        : { domain: cli.pigsty  ,endpoint: "127.0.0.1:8886" }      
  
      nginx_navbar:                    # application nav links on home page      
        - { name: PGWeb      , url : 'http://cli.pigsty'  , comment: 'PGWEB Browser Client'     }      
        - { name: PostgREST  , url : 'http://api.pigsty'  , comment: 'Kong API Gateway'         }
        - { name: Explain    , url : '/pigsty/pev.html'   , comment: 'pgsql explain visualizer' }
        - { name: Package    , url : '/pigsty'            , comment: 'local yum repo packages'  }
        - { name: PG Logs    , url : '/logs'              , comment: 'postgres raw csv logs'    }
        - { name: Schemas    , url : '/schema'            , comment: 'schemaspy summary report' }
        - { name: Reports    , url : '/report'            , comment: 'pgbadger summary report'  }
      node_timezone: Europe/Berlin     # use Europe/Berlin Timezone
      node_ntp_servers:                 # NTP servers in /etc/chrony.conf
        - pool 0.de.pool.ntp.org iburst
        - pool ${admin_ip} iburst       # assume non-admin nodes does not have internet access
      node_etc_hosts: [ '${admin_ip} h.pigsty a.pigsty p.pigsty g.pigsty sss.pigsty' ]
      dns_records: [ "${admin_ip} api.pigsty adm.pigsty cli.pigsty ddl.pigsty lab.pigsty git.pigsty sss.pigsty wiki.pigsty" ]
      pgbackrest_method: local          # if you want to use minio as backup repo instead of 'local' fs, uncomment this
...`

**Comment by Vonng** [comment]
Regarding the first question:

A complete HA deployment in a production environment typically requires at least three nodes; a 2-node setup can only achieve limited HA. The dual template [[here](https://github.com/Vonng/pigsty/blob/main/conf/sandbox/dual.yml#L19)](https://github.com/Vonng/pigsty/blob/main/conf/sandbox/dual.yml#L19) describes that if an entire infrastructure node goes down in this scenario, there is nothing we can do here.

As for the second question, the Up/Live status displayed here does not represent the state of a single Postgres or Pgbouncer process but rather the health status of the entire process family (Postgres, Patroni, Pgbouncer, Pg_exporter, HAProxy, VIP manager, etc.). Any unavailable component will be highlighted in the red status.
