### ISSUE TITLE
Ip address issue

### ISSUE THREAD

**Issue by guquandaju012** [Vonng/pigsty#463]
Hi, i am new to the pigsty, during the installation procedure.
I've tried the ip address which is shown in the up's video. "10.10.10.9" I found that it occur in the candinate list
but for my ubuntu 22.04, it didn't shown.
I've tried the "10.10.10.9" then failed.
![image](https://github.com/user-attachments/assets/0cd620ae-9616-433b-bb4d-02ea78436c5e)
If anyone can give me some advice on it?
Thanks and best Regards.

**Comment by Vonng** [comment]
The IP address (`10.10.10.x`) is for illustration purpose, please use your real IP address instead, such as 192.168.8.238 here.

**Comment by guquandaju012** [comment]
Thanks a lot, i've tried 192.168.8.238 then the following error came out, it seems that jinja2 version may lead to the error, i've tried to update the version to the lastest 3.1.4 but problem still remains, what kinds of version for jinja2 is compatible with the package please kindly suggest.

![image](https://github.com/user-attachments/assets/e7d56f95-de0b-4a30-b05b-b42ce87d0cc4)


> The IP address (`10.10.10.x`) is for illustration purpose, please use your real IP address instead, such as 192.168.8.238 here.
