### ISSUE TITLE
What should I do after I update configurations in pigsty.yml?

### ISSUE THREAD

**Issue by timeswind** [Vonng/pigsty#467]
I am still learning the relationship between different configuration files, but I have no confidence on which command to execute after I modified some parameters in some yml files such as adding new users in `pigsty.yml`.

Could anyone help me understand the procedure for updating the pigsty service after updating each configuration files?

**Comment by Vonng** [comment]
The configuration file is a provisioning blueprint, which means it create something as is, then you are on your own. You may reuse the playbook for some administartion tasks, check https://pigsty.io/docs/pgsql/admin and other module's admin docs for available admin options.
