### ISSUE TITLE
I encountered an error while creating the offline package.

### ISSUE THREAD

**Issue by Shercode** [Vonng/pigsty#468]
lly@pigsty-allinone:~/pigsty$ ./cache.yml -l infra

PLAY [CREATE LOCAL DIR] *******************************************************************************************************************************************************************************************
skipping: no hosts matched

PLAY [MAKE OFFLINE PACKAGE] ***************************************************************************************************************************************************************************************

TASK [node_id : get node fact] ************************************************************************************************************************************************************************************
changed: [192.168.1.125]

TASK [node_id : set node fact] ************************************************************************************************************************************************************************************
ok: [192.168.1.125]

TASK [node_id : fill empty nodename with hostname] ****************************************************************************************************************************************************************
skipping: [192.168.1.125]

TASK [node_id : build node identity] ******************************************************************************************************************************************************************************
ok: [192.168.1.125]

TASK [node_id : load debian.12 x86_64 vars] ***********************************************************************************************************************************************************************
ok: [192.168.1.125]

TASK [node_id : print node identity] ******************************************************************************************************************************************************************************
ok: [192.168.1.125] => {
    "msg": "nodename: pg-meta-1, node_cluster: pg-meta, spec: c4m4, os: debian.12.x86_64 d12:deb, [ADMIN] [INFRA] [PGSQL: pg-meta]  [ETCD: etcd]   "
}

TASK [cache : calculate offline package names] ********************************************************************************************************************************************************************
ok: [192.168.1.125]

TASK [cache : check repo dirs exists & not empty] *****************************************************************************************************************************************************************
ok: [192.168.1.125] => (item=pigsty)

TASK [cache : cache grafana plugins] ******************************************************************************************************************************************************************************
skipping: [192.168.1.125]

TASK [cache : create and trim local repo] *************************************************************************************************************************************************************************
changed: [192.168.1.125]

TASK [cache : create cache tarball] *******************************************************************************************************************************************************************************
changed: [192.168.1.125]

TASK [cache : fetch cache tarball from target node] ***************************************************************************************************************************************************************
fatal: [192.168.1.125]: FAILED! => {"changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --archive --rsh='/usr/bin/ssh -S none -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' --out-format='<<CHANGED>>%i %n%L' 192.168.1.125:/tmp/pkg.tgz /home/lly/pigsty/dist/v3.1.0/pigsty-pkg-v3.1.0.d12.x86_64.tgz", "msg": "Warning: Permanently added '192.168.1.125' (ED25519) to the list of known hosts.\r\nrsync: [Receiver] change_dir#3 \"/home/lly/pigsty/dist/v3.1.0\" failed: No such file or directory (2)\nrsync error: errors selecting input/output files, dirs (code 3) at main.c(829) [Receiver=3.2.7]\n", "rc": 3}

PLAY RECAP ********************************************************************************************************************************************************************************************************
192.168.1.125              : ok=9    changed=3    unreachable=0    failed=1    skipped=2    rescued=0    ignored=0

lly@pigsty-allinone:~/pigsty$ ls -l /home/lly/pigsty/dist
ls: cannot access '/home/lly/pigsty/dist': No such file or directory
lly@pigsty-allinone:~/pigsty$ mkdir -p dist/v3.1.0
lly@pigsty-allinone:~/pigsty$ ./cache.yml -l infra

PLAY [CREATE LOCAL DIR] *******************************************************************************************************************************************************************************************
skipping: no hosts matched

PLAY [MAKE OFFLINE PACKAGE] ***************************************************************************************************************************************************************************************

TASK [node_id : get node fact] ************************************************************************************************************************************************************************************
changed: [192.168.1.125]

TASK [node_id : set node fact] ************************************************************************************************************************************************************************************
ok: [192.168.1.125]

TASK [node_id : fill empty nodename with hostname] ****************************************************************************************************************************************************************
skipping: [192.168.1.125]

TASK [node_id : build node identity] ******************************************************************************************************************************************************************************
ok: [192.168.1.125]

TASK [node_id : load debian.12 x86_64 vars] ***********************************************************************************************************************************************************************
ok: [192.168.1.125]

TASK [node_id : print node identity] ******************************************************************************************************************************************************************************
ok: [192.168.1.125] => {
    "msg": "nodename: pg-meta-1, node_cluster: pg-meta, spec: c4m4, os: debian.12.x86_64 d12:deb, [ADMIN] [INFRA] [PGSQL: pg-meta]  [ETCD: etcd]   "
}

TASK [cache : calculate offline package names] ********************************************************************************************************************************************************************
ok: [192.168.1.125]

TASK [cache : check repo dirs exists & not empty] *****************************************************************************************************************************************************************
ok: [192.168.1.125] => (item=pigsty)

TASK [cache : cache grafana plugins] ******************************************************************************************************************************************************************************
skipping: [192.168.1.125]

TASK [cache : create and trim local repo] *************************************************************************************************************************************************************************
changed: [192.168.1.125]

TASK [cache : create cache tarball] *******************************************************************************************************************************************************************************
changed: [192.168.1.125]

TASK [cache : fetch cache tarball from target node] ***************************************************************************************************************************************************************
changed: [192.168.1.125]

PLAY [CREATE LOCAL DIR] *******************************************************************************************************************************************************************************************
skipping: no hosts matched

PLAY RECAP ********************************************************************************************************************************************************************************************************
192.168.1.125              : ok=10   changed=4    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0

**Comment by Vonng** [comment]
use `make release` to create the local release directory first. will add description on the docs later, thanks for the feedback.
