### ISSUE TITLE
Site  wrong link 

### ISSUE THREAD

**Issue by waitingsong** [Vonng/pigsty#472]
https://pigsty.cc/zh/docs/setup/install/

```
如果您觉得 Pigsty 的组件过于复杂，还可以考虑使用 [最小化安装](https://pigsty.cc/zh/docs/setup/install/mini) ，
```
wrong link: `https://pigsty.cc/zh/docs/setup/install/mini`

correct link for EN: `https://pigsty.cc/docs/setup/slim/`

**Comment by Vonng** [comment]
Fixed, thanks for your feedback~
