### ISSUE TITLE
PG Instance Overview not changed after switching Instance

### ISSUE THREAD

**Issue by waitingsong** [Vonng/pigsty#474]
See pic

![pigsty-2024-12-05_110736](https://github.com/user-attachments/assets/7e008af1-baba-4a07-8798-634b25d35c47)

**Comment by Vonng** [comment]
haproxy instance name is bind to nodename (node's `ins` identity). have you overwrite the node's ideneity yet? 

with `./node.yml -t reigster_prometheus`

**Comment by waitingsong** [comment]
是 Instance 下拉联动 Overview 失败： 切换 Instacnce 之后 F5 后 Overview 是正常的。

**Comment by Vonng** [comment]
Resolved and release by v3.2.0
