### ISSUE TITLE
Page:  pgsql-pgbounce instance select empty

### ISSUE THREAD

**Issue by waitingsong** [Vonng/pigsty#477]
pgsql-pgbounce instance select not works
1. open dashboards: `http://g.pigsty/dashboards/f/pgsql/`
2. enter [PGSQL Pgbouncer](http://g.pigsty/d/pgsql-pgbouncer/pgsql-pgbouncer)
3. **instance select empty**

the url is `http://g.pigsty/d/pgsql-pgbouncer/pgsql-pgbouncer?from=2023-08-01T00:17:29.230Z&to=2023-08-01T02:35:39.634Z&var-ins=&var-ip=&var-seq=&var-cls=&var-node=`
![p2024-12-07_220555](https://github.com/user-attachments/assets/0d1f453e-a1ff-4802-a0a6-ce90d2438c5a)

But this works:
1. open dashboards: `http://g.pigsty/dashboards/f/pgsql/`
2. enter [PGSQL Cluster](http://g.pigsty/d/pgsql-cluster/pgsql-cluster)
3. enter `pgbouncer` 
   ![p2024-12-07_220924](https://github.com/user-attachments/assets/87f8a7bf-e27c-4d66-8591-13b1ae7061a2)
4. **instance select contains items**

the url is `http://g.pigsty/d/pgsql-pgbouncer/pgsql-pgbouncer?var-ins=pg-a-113&from=now-1h&to=now&var-ip=10.0.1.13&var-seq=113&var-cls=pg-a&var-node=10.0.1.3`
**with query `var-ins=pg-a-113`**

![p2024-12-07_221118](https://github.com/user-attachments/assets/5204e5f3-c78e-48b0-9318-8077d210751c)

**Comment by Vonng** [comment]
Resolved and released by v3.2.0a
