### ISSUE TITLE
./configure -c full  my IP is 192.168.31.68 

### ISSUE THREAD

**Issue by jetchan88** [Vonng/pigsty#486]
./configure -c full
[WARN] Multiple IP address candidates found:
    (1) 10.0.2.15           inet 10.0.2.15/24 metric 100 brd 10.0.2.255 scope global dynamic enp0s3
    (2) 192.168.31.68       inet 192.168.31.68/24 brd 192.168.31.255 scope global enp0s8
[ IN ] INPUT primary_ip address (of current meta node, e.g 10.10.10.10):
=> 192.168.31.68
[ OK ] primary_ip = 192.168.31.68 (from input)
[ OK ] admin = root@192.168.31.68 ok
[WARN] user = root is not recommended, sure?
[ OK ] mode = full (manually set)
[ OK ] configure pigsty done

cat  pigsty.yml     <===10.10.10. subnet not replaced by 192.168.8.
-----------------
    # minio cluster, s3 compatible object storage
    minio: { hosts: { 192.168.31.68: { minio_seq: 1 } }, vars: { minio_cluster: minio } }

    # postgres example cluster: pg-meta
    pg-meta:
      hosts: { 192.168.31.68: { pg_seq: 1, pg_role: primary } }
      vars:
        pg_cluster: pg-meta
        pg_users:
          - { name: dbuser_meta ,password: DBUser.Meta     ,pgbouncer: true ,roles: [ dbrole_admin ]    ,comment: pigsty admin user }
          - { name: dbuser_view ,password: DBUser.Viewer   ,pgbouncer: true ,roles: [ dbrole_readonly ] ,comment: read-only viewer for meta database }
        pg_databases:
          - { name: meta ,baseline: cmdb.sql ,comment: pigsty meta database ,schemas: [ pigsty ] }
        pg_hba_rules:
          - { user: dbuser_view , db: all ,addr: infra ,auth: pwd ,title: 'allow grafana dashboard access cmdb from infra nodes' }
        pg_vip_enabled: true
        pg_vip_address: 10.10.10.2/24
        pg_vip_interface: eth1

    # pgsql 3 node ha cluster: pg-test
    pg-test:
      hosts:
        10.10.10.11: { pg_seq: 1, pg_role: primary }   # primary instance, leader of cluster
        10.10.10.12: { pg_seq: 2, pg_role: replica }   # replica instance, follower of leader
        10.10.10.13: { pg_seq: 3, pg_role: replica, pg_offline_query: true } # replica with offline access
      vars:
        pg_cluster: pg-test           # define pgsql cluster name
        pg_users:  [{ name: test , password: test , pgbouncer: true , roles: [ dbrole_admin ] }]
        pg_databases: [{ name: test }]
        pg_vip_enabled: true
        pg_vip_address: 10.10.10.3/24
        pg_vip_interface: eth1

    #----------------------------------#
    # redis ms, sentinel, native cluster
    #----------------------------------#
    redis-ms: # redis classic primary & replica
      hosts: { 192.168.31.68: { redis_node: 1 , redis_instances: { 6379: { }, 6380: { replica_of: '192.168.31.68 6379' } } } }
      vars: { redis_cluster: redis-ms ,redis_password: 'redis.ms' ,redis_max_memory: 64MB }

    redis-meta: # redis sentinel x 3
      hosts: { 10.10.10.11: { redis_node: 1 , redis_instances: { 26379: { } ,26380: { } ,26381: { } } } }
      vars:
        redis_cluster: redis-meta
        redis_password: 'redis.meta'
        redis_mode: sentinel
        redis_max_memory: 16MB
        redis_sentinel_monitor: # primary list for redis sentinel, use cls as name, primary ip:port
          - { name: redis-ms, host: 192.168.31.68, port: 6379 ,password: redis.ms, quorum: 2 }

    redis-test: # redis native cluster: 3m x 3s
      hosts:
        10.10.10.12: { redis_node: 1 ,redis_instances: { 6379: { } ,6380: { } ,6381: { } } }
        10.10.10.13: { redis_node: 2 ,redis_instances: { 6379: { } ,6380: { } ,6381: { } } }
      vars: { redis_cluster: redis-test ,redis_password: 'redis.test' ,redis_mode: cluster, redis_max_memory: 32MB }

**Comment by Vonng** [comment]
This behavior is documented at https://pigsty.cc/docs/conf/full/ 

`configure` is merely an auxiliary wrapper script for new users (aims for quick single node install). It would be too complicated to ask for four ip address rather than change them in the config file. 

But we may later enhance `configure` in the [cli tool](https://github.com/pgsty/pig/blob/main/cmd/sty.go#L175) to make it easier to use.
