### ISSUE TITLE
about parameter max_prepared_transactions cause Pending Restart

### ISSUE THREAD

**Issue by xiangma0510** [Vonng/pigsty#54]
When I install the patroni cluster use pigsty，it set the parameter max_prepared_transactions to 0 default , in postgresql streaming replication,It not permitted,it always cause patroni prompt following:
![image](https://user-images.githubusercontent.com/86297429/128832311-93344b44-26c9-4929-90f5-a13a12ed987c.png)

**Comment by Vonng** [comment]
Any details?

**Comment by xiangma0510** [comment]
It is recommended that you increase the value of this parameter instead of setting it to 0，I increase the values，the prompt disappeared.

**Comment by xiangma0510** [comment]
I checked the parameter in docs, maybe as a hot standby replica,it cannot be set to 0

**Comment by xiangma0510** [comment]
zalando/patroni
issue #[2027](https://github.com/zalando/patroni/issues/2027)
[1922](https://github.com/zalando/patroni/issues/1922)

**Comment by Vonng** [comment]
Guess the extension `citus` in `shared_preload_libraries`  enforce a higher value of `max_prepared_transactions` .
The hot fix solution is removing citus from `pg_shared_libraries` or increase `max_prepared_transactions`
This will be fixed immediately and release in  minor release.

**Comment by xiangma0510** [comment]
there is another problem，after installed I cannot open the consul ui directly, I change the systemd services to open it,It looks like, the port 8500 only listen by 127.0.0.1 in server node，Please insure it

**Comment by xiangma0510** [comment]
直接用中文好不

**Comment by Vonng** [comment]
> there is another problem，after installed I cannot open the consul ui directly, I change the systemd services to open it,It looks like, the port 8500 only listen by 127.0.0.1 in server node，Please insure it

Yes that is deliberate to do so. Consul UI is the only exception which should be access via Nginx due to security reason.

**Comment by Vonng** [comment]
fixed by https://github.com/Vonng/pigsty/commit/43bd7d0dd3524362b5e8bc1d63a9454bf42544c1 (removing citus from default shared preload libraries)
