### ISSUE TITLE
how to install without internet?

### ISSUE THREAD

**Issue by reyhgao** [Vonng/pigsty#57]
./configure -m tiny
make install

then I got this below:

TASK [node : Install local repo] *******************************************************************************************
failed: [192.168.68.165] (item=http://yum.pigsty/pigsty.repo) => {"ansible_loop_var": "item", "changed": false, "dest": "/etc/yum.repos.d/pigsty.repo", "elapsed": 0, "item": "http://yum.pigsty/pigsty.repo", "msg": "Request failed", "response": "HTTP Error 403: Forbidden", "status_code": 403, "url": "http://yum.pigsty/pigsty.repo"}

**Comment by Vonng** [comment]
If you already have `/tmp/pkg.tgz`. The installation does not require internet procedure.
While the node do need HTTP access to admin node's local yum repo. 
Which is `http://yum.pigsty/pigsty.repo` , and the yum.pigsty is a static DNS record that write to node's `/etc/hosts`.

Try access `curl http://yum.pigsty/pigsty.repo` on that node (`192.168.68.165`) and see if it works.
Looks like something related with firewall, selinux, network security policy, etc...

**Comment by reyhgao** [comment]
This problem is solved. 
The directory /www/pigsty generated belongs to root, I switched its owner to Nginx.
