### ISSUE TITLE
Make install failed with TASK  [Install node basic packages]

### ISSUE THREAD

**Issue by reyhgao** [Vonng/pigsty#60]
1. without the Internet
2. under CentOS7.6, not CentOS7.8
3. ./configure runs OK but one WARN
4. make install got stuck with TASK [Install node basic packages],  shown below

[root@pigsty pigsty]# ./configure -i 192.168.68.165 -m tiny
configure pigsty v1.0.0 begin
[ OK ] kernel = Linux
[ OK ] machine = x86_64
[WARN] release = 7.6.1810 , it's fine. But beware that 'pkg.tgz' are made under 7.8
HINT: If something goes wrong with minor version. Consider bootstrap via Internet without pkg.tgz.[ OK ] sudo = root ok
[ OK ] ssh = root@127.0.0.1 ok
[ OK ] primary_ip = 92.168.68.165 (from argument)
[ OK ] admin = root@192.168.68.165 ok
[ OK ] mode = tiny (manually set)
[ OK ] config = tiny@192.168.68.165
[ OK ] cache = /tmp/pkg.tgz exists
[ OK ] repo = /www/pigsty ok
[ OK ] repo file = /etc/yum.repos.d/pigsty-local.repo
[ OK ] utils = install from local file repo
[ OK ] ansible = ansible 2.9.25
configure pigsty done. Use 'make install' to proceed
[root@pigsty pigsty]# make install

TASK [Install node basic packages] *************************************************************************************************************************************************************************************
failed: [192.168.68.165] (item=[u'wget,yum-utils,sshpass,ntp,chrony,tuned,uuid,lz4,vim-minimal,make,patch,bash,lsof,wget,unzip,git,readline,zlib,openssl', u'numactl,grubby,sysstat,dstat,iotop,bind-utils,net-tools,tcpdump,socat,ipvsadm,telnet,tuned,pv,jq', u'python3,python3-psycopg2,python36-requests,python3-etcd,python3-consul', u'python36-urllib3,python36-idna,python36-pyOpenSSL,python36-cryptography', u'node_exporter,consul,consul-template,etcd,haproxy,keepalived,vip-manager']) => {"ansible_loop_var": "item", "changed": false, "changes": {"installed": ["uuid", "patch", "git", "numactl", "dstat", "iotop", "socat", "ipvsadm", "telnet", "pv", "jq", "python3", "python3-psycopg2", "python36-requests", "python3-etcd", "python3-consul", "python36-urllib3", "python36-idna", "python36-pyOpenSSL", "python36-cryptography", "node_exporter", "consul", "consul-template", "etcd", "haproxy", "keepalived", "vip-manager"]}, "item": ["wget,yum-utils,sshpass,ntp,chrony,tuned,uuid,lz4,vim-minimal,make,patch,bash,lsof,wget,unzip,git,readline,zlib,openssl", "numactl,grubby,sysstat,dstat,iotop,bind-utils,net-tools,tcpdump,socat,ipvsadm,telnet,tuned,pv,jq", "python3,python3-psycopg2,python36-requests,python3-etcd,python3-consul", "python36-urllib3,python36-idna,python36-pyOpenSSL,python36-cryptography", "node_exporter,consul,consul-template,etcd,haproxy,keepalived,vip-manager"], "msg": "Error: Package: ipset-6.38-2.el7.x86_64 (@anaconda)\n           Requires: libipset.so.11(LIBIPSET_1.0)(64bit)\n           Removing: ipset-libs-6.38-2.el7.x86_64 (@anaconda)\n               libipset.so.11(LIBIPSET_1.0)(64bit)\n           Updated By: ipset-libs-7.1-1.el7.x86_64 (pigsty)\n              ~libipset.so.13(LIBIPSET_4.9)(64bit)\n              ~libipset.so.13(LIBIPSET_4.8)(64bit)\n              ~libipset.so.13(LIBIPSET_4.7)(64bit)\n              ~libipset.so.13(LIBIPSET_4.6)(64bit)\n              ~libipset.so.13(LIBIPSET_4.5)(64bit)\n              ~libipset.so.13(LIBIPSET_4.4)(64bit)\n              ~libipset.so.13(LIBIPSET_4.3)(64bit)\n              ~libipset.so.13(LIBIPSET_4.2)(64bit)\n              ~libipset.so.13(LIBIPSET_4.1)(64bit)\n              ~libipset.so.13(LIBIPSET_4.0)(64bit)\n              ~libipset.so.13(LIBIPSET_3.0)(64bit)\n              ~libipset.so.13(LIBIPSET_2.0)(64bit)\n              ~libipset.so.13(LIBIPSET_1.0)(64bit)\nError: Package: ipset-6.38-2.el7.x86_64 (@anaconda)\n           Requires: libipset.so.11()(64bit)\n           Removing: ipset-libs-6.38-2.el7.x86_64 (@anaconda)\n               libipset.so.11()(64bit)\n           Updated By: ipset-libs-7.1-1.el7.x86_64 (pigsty)\n              ~libipset.so.13()(64bit)\nError: Package: ipset-6.38-2.el7.x86_64 (@anaconda)\n           Requires: libipset.so.11(LIBIPSET_4.5)(64bit)\n           Removing: ipset-libs-6.38-2.el7.x86_64 (@anaconda)\n               libipset.so.11(LIBIPSET_4.5)(64bit)\n           Updated By: ipset-libs-7.1-1.el7.x86_64 (pigsty)\n              ~libipset.so.13(LIBIPSET_4.9)(64bit)\n              ~libipset.so.13(LIBIPSET_4.8)(64bit)\n              ~libipset.so.13(LIBIPSET_4.7)(64bit)\n              ~libipset.so.13(LIBIPSET_4.6)(64bit)\n              ~libipset.so.13(LIBIPSET_4.5)(64bit)\n              ~libipset.so.13(LIBIPSET_4.4)(64bit)\n              ~libipset.so.13(LIBIPSET_4.3)(64bit)\n              ~libipset.so.13(LIBIPSET_4.2)(64bit)\n              ~libipset.so.13(LIBIPSET_4.1)(64bit)\n              ~libipset.so.13(LIBIPSET_4.0)(64bit)\n              ~libipset.so.13(LIBIPSET_3.0)(64bit)\n              ~libipset.so.13(LIBIPSET_2.0)(64bit)\n              ~libipset.so.13(LIBIPSET_1.0)(64bit)\nError: Package: ipset-6.38-2.el7.x86_64 (@anaconda)\n           Requires: ipset-libs(x86-64) = 6.38-2.el7\n           Removing: ipset-libs-6.38-2.el7.x86_64 (@anaconda)\n               ipset-libs(x86-64) = 6.38-2.el7\n           Updated By: ipset-libs-7.1-1.el7.x86_64 (pigsty)\n               ipset-libs(x86-64) = 7.1-1.el7\nError: Package: ipset-6.38-2.el7.x86_64 (@anaconda)\n           Requires: libipset.so.11(LIBIPSET_4.6)(64bit)\n           Removing: ipset-libs-6.38-2.el7.x86_64 (@anaconda)\n               libipset.so.11(LIBIPSET_4.6)(64bit)\n           Updated By: ipset-libs-7.1-1.el7.x86_64 (pigsty)\n              ~libipset.so.13(LIBIPSET_4.9)(64bit)\n              ~libipset.so.13(LIBIPSET_4.8)(64bit)\n              ~libipset.so.13(LIBIPSET_4.7)(64bit)\n              ~libipset.so.13(LIBIPSET_4.6)(64bit)\n              ~libipset.so.13(LIBIPSET_4.5)(64bit)\n              ~libipset.so.13(LIBIPSET_4.4)(64bit)\n              ~libipset.so.13(LIBIPSET_4.3)(64bit)\n              ~libipset.so.13(LIBIPSET_4.2)(64bit)\n              ~libipset.so.13(LIBIPSET_4.1)(64bit)\n              ~libipset.so.13(LIBIPSET_4.0)(64bit)\n              ~libipset.so.13(LIBIPSET_3.0)(64bit)\n              ~libipset.so.13(LIBIPSET_2.0)(64bit)\n              ~libipset.so.13(LIBIPSET_1.0)(64bit)\nError: Package: ipset-6.38-2.el7.x86_64 (@anaconda)\n           Requires: libipset.so.11(LIBIPSET_3.0)(64bit)\n           Removing: ipset-libs-6.38-2.el7.x86_64 (@anaconda)\n               libipset.so.11(LIBIPSET_3.0)(64bit)\n           Updated By: ipset-libs-7.1-1.el7.x86_64 (pigsty)\n              ~libipset.so.13(LIBIPSET_4.9)(64bit)\n              ~libipset.so.13(LIBIPSET_4.8)(64bit)\n              ~libipset.so.13(LIBIPSET_4.7)(64bit)\n              ~libipset.so.13(LIBIPSET_4.6)(64bit)\n              ~libipset.so.13(LIBIPSET_4.5)(64bit)\n              ~libipset.so.13(LIBIPSET_4.4)(64bit)\n              ~libipset.so.13(LIBIPSET_4.3)(64bit)\n              ~libipset.so.13(LIBIPSET_4.2)(64bit)\n              ~libipset.so.13(LIBIPSET_4.1)(64bit)\n              ~libipset.so.13(LIBIPSET_4.0)(64bit)\n              ~libipset.so.13(LIBIPSET_3.0)(64bit)\n              ~libipset.so.13(LIBIPSET_2.0)(64bit)\n              ~libipset.so.13(LIBIPSET_1.0)(64bit)\nError: Package: ipset-6.38-2.el7.x86_64 (@anaconda)\n           Requires: libipset.so.11(LIBIPSET_2.0)(64bit)\n           Removing: ipset-libs-6.38-2.el7.x86_64 (@anaconda)\n               libipset.so.11(LIBIPSET_2.0)(64bit)\n           Updated By: ipset-libs-7.1-1.el7.x86_64 (pigsty)\n              ~libipset.so.13(LIBIPSET_4.9)(64bit)\n              ~libipset.so.13(LIBIPSET_4.8)(64bit)\n              ~libipset.so.13(LIBIPSET_4.7)(64bit)\n              ~libipset.so.13(LIBIPSET_4.6)(64bit)\n              ~libipset.so.13(LIBIPSET_4.5)(64bit)\n              ~libipset.so.13(LIBIPSET_4.4)(64bit)\n              ~libipset.so.13(LIBIPSET_4.3)(64bit)\n              ~libipset.so.13(LIBIPSET_4.2)(64bit)\n              ~libipset.so.13(LIBIPSET_4.1)(64bit)\n              ~libipset.so.13(LIBIPSET_4.0)(64bit)\n              ~libipset.so.13(LIBIPSET_3.0)(64bit)\n              ~libipset.so.13(LIBIPSET_2.0)(64bit)\n              ~libipset.so.13(LIBIPSET_1.0)(64bit)\n", "rc": 1, "results": ["wget-1.14-18.el7_6.1.x86_64 providing wget is already installed", "yum-utils-1.1.31-54.el7_8.noarch providing yum-utils is already installed", "sshpass-1.06-2.el7.x86_64 providing sshpass is already installed", "ntp-4.2.6p5-28.el7.centos.x86_64 providing ntp is already installed", "chrony-3.2-2.el7.x86_64 providing chrony is already installed", "tuned-2.10.0-6.el7.noarch providing tuned is already installed", "lz4-1.7.5-2.el7.x86_64 providing lz4 is already installed", "2:vim-minimal-7.4.160-5.el7.x86_64 providing vim-minimal is already installed", "1:make-3.82-23.el7.x86_64 providing make is already installed", "bash-4.2.46-31.el7.x86_64 providing bash is already installed", "lsof-4.87-6.el7.x86_64 providing lsof is already installed", "wget-1.14-18.el7_6.1.x86_64 providing wget is already installed", "unzip-6.0-22.el7_9.x86_64 providing unzip is already installed", "readline-6.2-10.el7.x86_64 providing readline is already installed", "zlib-1.2.7-18.el7.x86_64 providing zlib is already installed", "1:openssl-1.0.2k-16.el7.x86_64 providing openssl is already installed", "grubby-8.28-25.el7.x86_64 providing grubby is already installed", "sysstat-10.1.5-17.el7.x86_64 providing sysstat is already installed", "32:bind-utils-9.9.4-72.el7.x86_64 providing bind-utils is already installed", "net-tools-2.0-0.24.20131004git.el7.x86_64 providing net-tools is already installed", "14:tcpdump-4.9.2-3.el7.x86_64 providing tcpdump is already installed", "tuned-2.10.0-6.el7.noarch providing tuned is already installed", "Loaded plugins: fastestmirror, langpacks\nLoading mirror speeds from cached hostfile\nResolving Dependencies\n--> Running transaction check\n---> Package consul.x86_64 0:1.10.1-1.el7.harbottle will be installed\n---> Package consul-template.x86_64 0:0.25.1-1.rhel7 will be installed\n---> Package dstat.noarch 0:0.7.2-12.el7 will be installed\n---> Package etcd.x86_64 0:3.3.11-2.el7.centos will be installed\n---> Package git.x86_64 0:1.8.3.1-23.el7_8 will be installed\n--> Processing Dependency: perl-Git = 1.8.3.1-23.el7_8 for package: git-1.8.3.1-23.el7_8.x86_64\n--> Processing Dependency: perl(Term::ReadKey) for package: git-1.8.3.1-23.el7_8.x86_64\n--> Processing Dependency: perl(Git) for package: git-1.8.3.1-23.el7_8.x86_64\n--> Processing Dependency: perl(Error) for package: git-1.8.3.1-23.el7_8.x86_64\n---> Package haproxy.x86_64 0:2.2.12-1.el7 will be installed\n---> Package iotop.noarch 0:0.6-4.el7 will be installed\n---> Package ipvsadm.x86_64 0:1.27-8.el7 will be installed\n---> Package jq.x86_64 0:1.6-2.el7 will be installed\n--> Processing Dependency: libonig.so.5()(64bit) for package: jq-1.6-2.el7.x86_64\n---> Package keepalived.x86_64 0:1.3.5-19.el7 will be installed\n--> Processing Dependency: ipset-libs >= 7.1 for package: keepalived-1.3.5-19.el7.x86_64\n--> Processing Dependency: libnetsnmpmibs.so.31()(64bit) for package: keepalived-1.3.5-19.el7.x86_64\n--> Processing Dependency: libnetsnmpagent.so.31()(64bit) for package: keepalived-1.3.5-19.el7.x86_64\n---> Package node_exporter.x86_64 0:1.2.0-1.el7 will be installed\n---> Package numactl.x86_64 0:2.0.12-5.el7 will be installed\n---> Package patch.x86_64 0:2.7.1-12.el7_7 will be installed\n---> Package pv.x86_64 0:1.4.6-1.el7 will be installed\n---> Package python3.x86_64 0:3.6.8-18.el7 will be installed\n--> Processing Dependency: python3-libs(x86-64) = 3.6.8-18.el7 for package: python3-3.6.8-18.el7.x86_64\n--> Processing Dependency: python3-setuptools for package: python3-3.6.8-18.el7.x86_64\n--> Processing Dependency: python3-pip for package: python3-3.6.8-18.el7.x86_64\n--> Processing Dependency: libpython3.6m.so.1.0()(64bit) for package: python3-3.6.8-18.el7.x86_64\n---> Package python3-consul.noarch 0:1.1.0-1.rhel7 will be installed\n---> Package python3-etcd.noarch 0:0.4.5-20.rhel7 will be installed\n---> Package python3-psycopg2.x86_64 0:2.8.6-1.rhel7 will be installed\n--> Processing Dependency: libpq5 >= 10.0 for package: python3-psycopg2-2.8.6-1.rhel7.x86_64\n--> Processing Dependency: libpq.so.5()(64bit) for package: python3-psycopg2-2.8.6-1.rhel7.x86_64\n---> Package python36-cryptography.x86_64 0:2.3-2.el7 will be installed\n--> Processing Dependency: python36-six >= 1.4.1 for package: python36-cryptography-2.3-2.el7.x86_64\n--> Processing Dependency: python36-cffi >= 1.7 for package: python36-cryptography-2.3-2.el7.x86_64\n--> Processing Dependency: python36-asn1crypto >= 0.21 for package: python36-cryptography-2.3-2.el7.x86_64\n---> Package python36-idna.noarch 0:2.10-1.el7 will be installed\n---> Package python36-pyOpenSSL.noarch 0:17.3.0-1.el7 will be installed\n---> Package python36-requests.noarch 0:2.14.2-2.el7 will be installed\n--> Processing Dependency: python36-chardet for package: python36-requests-2.14.2-2.el7.noarch\n---> Package python36-urllib3.noarch 0:1.25.6-2.el7 will be installed\n--> Processing Dependency: python36-pysocks for package: python36-urllib3-1.25.6-2.el7.noarch\n---> Package socat.x86_64 0:1.7.3.2-2.el7 will be installed\n---> Package telnet.x86_64 1:0.17-66.el7 will be installed\n---> Package uuid.x86_64 0:1.6.2-26.el7 will be installed\n---> Package vip-manager.x86_64 0:1.0_1-1 will be installed\n--> Running transaction check\n---> Package ipset-libs.x86_64 0:6.38-2.el7 will be updated\n--> Processing Dependency: ipset-libs(x86-64) = 6.38-2.el7 for package: ipset-6.38-2.el7.x86_64\n--> Processing Dependency: libipset.so.11()(64bit) for package: ipset-6.38-2.el7.x86_64\n--> Processing Dependency: libipset.so.11(LIBIPSET_1.0)(64bit) for package: ipset-6.38-2.el7.x86_64\n--> Processing Dependency: libipset.so.11(LIBIPSET_2.0)(64bit) for package: ipset-6.38-2.el7.x86_64\n--> Processing Dependency: libipset.so.11(LIBIPSET_3.0)(64bit) for package: ipset-6.38-2.el7.x86_64\n--> Processing Dependency: libipset.so.11(LIBIPSET_4.5)(64bit) for package: ipset-6.38-2.el7.x86_64\n--> Processing Dependency: libipset.so.11(LIBIPSET_4.6)(64bit) for package: ipset-6.38-2.el7.x86_64\n---> Package ipset-libs.x86_64 0:7.1-1.el7 will be an update\n---> Package libpq5.x86_64 0:13.3-11PGDG.rhel7 will be installed\n---> Package net-snmp-agent-libs.x86_64 1:5.7.2-49.el7_9.1 will be installed\n--> Processing Dependency: net-snmp-libs = 1:5.7.2-49.el7_9.1 for package: 1:net-snmp-agent-libs-5.7.2-49.el7_9.1.x86_64\n---> Package oniguruma.x86_64 0:6.8.2-1.el7 will be installed\n---> Package perl-Error.noarch 1:0.17020-2.el7 will be installed\n---> Package perl-Git.noarch 0:1.8.3.1-23.el7_8 will be installed\n---> Package perl-TermReadKey.x86_64 0:2.30-20.el7 will be installed\n---> Package python3-libs.x86_64 0:3.6.8-18.el7 will be installed\n---> Package python3-pip.noarch 0:9.0.3-8.el7 will be installed\n---> Package python3-setuptools.noarch 0:39.2.0-10.el7 will be installed\n---> Package python36-asn1crypto.noarch 0:0.24.0-7.el7 will be installed\n---> Package python36-cffi.x86_64 0:1.9.1-3.el7 will be installed\n--> Processing Dependency: python36-pycparser for package: python36-cffi-1.9.1-3.el7.x86_64\n---> Package python36-chardet.noarch 0:3.0.4-1.el7 will be installed\n---> Package python36-pysocks.noarch 0:1.6.8-7.el7 will be installed\n---> Package python36-six.noarch 0:1.14.0-3.el7 will be installed\n--> Running transaction check\n---> Package ipset-libs.x86_64 0:6.38-2.el7 will be updated\n--> Processing Dependency: ipset-libs(x86-64) = 6.38-2.el7 for package: ipset-6.38-2.el7.x86_64\n--> Processing Dependency: libipset.so.11()(64bit) for package: ipset-6.38-2.el7.x86_64\n--> Processing Dependency: libipset.so.11(LIBIPSET_1.0)(64bit) for package: ipset-6.38-2.el7.x86_64\n--> Processing Dependency: libipset.so.11(LIBIPSET_2.0)(64bit) for package: ipset-6.38-2.el7.x86_64\n--> Processing Dependency: libipset.so.11(LIBIPSET_3.0)(64bit) for package: ipset-6.38-2.el7.x86_64\n--> Processing Dependency: libipset.so.11(LIBIPSET_4.5)(64bit) for package: ipset-6.38-2.el7.x86_64\n--> Processing Dependency: libipset.so.11(LIBIPSET_4.6)(64bit) for package: ipset-6.38-2.el7.x86_64\n---> Package net-snmp-libs.x86_64 1:5.7.2-37.el7 will be updated\n---> Package net-snmp-libs.x86_64 1:5.7.2-49.el7_9.1 will be an update\n---> Package python36-pycparser.noarch 0:2.14-2.el7 will be installed\n--> Processing Dependency: python36-ply for package: python36-pycparser-2.14-2.el7.noarch\n--> Running transaction check\n---> Package ipset-libs.x86_64 0:6.38-2.el7 will be updated\n--> Processing Dependency: ipset-libs(x86-64) = 6.38-2.el7 for package: ipset-6.38-2.el7.x86_64\n--> Processing Dependency: libipset.so.11()(64bit) for package: ipset-6.38-2.el7.x86_64\n--> Processing Dependency: libipset.so.11(LIBIPSET_1.0)(64bit) for package: ipset-6.38-2.el7.x86_64\n--> Processing Dependency: libipset.so.11(LIBIPSET_2.0)(64bit) for package: ipset-6.38-2.el7.x86_64\n--> Processing Dependency: libipset.so.11(LIBIPSET_3.0)(64bit) for package: ipset-6.38-2.el7.x86_64\n--> Processing Dependency: libipset.so.11(LIBIPSET_4.5)(64bit) for package: ipset-6.38-2.el7.x86_64\n--> Processing Dependency: libipset.so.11(LIBIPSET_4.6)(64bit) for package: ipset-6.38-2.el7.x86_64\n---> Package python36-ply.noarch 0:3.9-2.el7 will be installed\n--> Finished Dependency Resolution\n You could try using --skip-broken to work around the problem\n You could try running: rpm -Va --nofiles --nodigest\n"]}

**Comment by reyhgao** [comment]
Error: Package: ipset-6.38-2.el7.x86_64 (@anaconda)
 Requires: libipset.so.11(LIBIPSET_4.6)(64bit)
 Removing: ipset-libs-6.38-2.el7.x86_64 (@anaconda)
 libipset.so.11(LIBIPSET_4.6)(64bit)
 Updated By: ipset-libs-7.1-1.el7.x86_64 (pigsty)

don't know why got this error message, then I tried rpm ivh  ipset-libs-7.1-1.el7.x86_64.rpm and passed this TASK.

**Comment by Vonng** [comment]
As the warn shows:

[WARN] release = 7.6.1810 , it's fine. But beware that 'pkg.tgz' are made under 7.8
HINT: If something goes wrong with minor version. Consider bootstrap via Internet without pkg.tgz.

Usually rpm install error could be resolve by using original upstream yum repo.


There's a hot-fix for this:

```bash
rm -rf /www/pigsty/repo_complete     # mark the repo as invalid.
rm -rf /www/pigsty/xxxxxx.                  # remove problematic rpms

./infra.yml -t repo                                  # try rebuild repo from upstream
```

It will download problematic packages only from viable upstream.
